### ISSUE TITLE
I sent an NFT LEGEND ( YUN#52) from a tanglepay account to soonaverse but it never arrived

### ISSUE THREAD

**Issue by Ruben8897** [soonaverse/app#102]
**Describe the bug**
I will explain everything from the beginning. 
I had in one of my soonaverse accounts ( https://soonaverse.com/member/0xb301e89f046091a647a036bb902cbf1afc64ba52/nfts ) 3 tanglepay nfts and i have sent the three nfts to another soonaverse account ( https://soonaverse.com/member/0xf2193cfe813dc427efd698e2a248ebea817e5979/nfts ), with them I created a legend nft.  I took them out of soonaverse to take them to firefly shimmer  smr1qzgwkam04tggj7zy0hzstskprwv5y8882r3es0xpevlcuaquvqf7kjhc4tr and then I took them to a tanglepay account  smr1qrydtqhdty6qean4t0a3m4llsn0qkymzedsugfeu24md84x7vg6rjweqh8n . I could only connect tanglepay to the tanglepay website to mine it. After minting it on tanglepay (YUN#52), I sent my nft to a firefly account to load the nft on soonaverse, but then decided to load it from tanglepay. From the tanglepay account I sent the nft to the address requested by soonaverse and it never arrived. 

I am sure I copied the address Soonaverse provided me to upload the nft to my Soonaverse account correctly, the countdown to send the NFT reached 0 and Soonaverse did not recognize the NFT submission.

**Expected behavior**
I hope I can recover my NFT, I am sure I did the procedure right and I copied and pasted the address that Soonaverse asked me to load the NFT in Soonaverse

**Screenshots**
![image](https://github.com/soonaverse/app/assets/114197646/fd110b26-dc3a-4325-ac59-94b9291f39a7)
![image](https://github.com/soonaverse/app/assets/114197646/4acd3528-2641-457a-8f2e-f960d9a5b4fb)
these are tanglepay's movements

![image](https://github.com/soonaverse/app/assets/114197646/f9b3e0e9-d238-43ed-aeb1-c2c629aed89a)
and these are firefly's movements

https://explorer.shimmer.network/shimmer/addr/smr1qrydtqhdty6qean4t0a3m4llsn0qkymzedsugfeu24md84x7vg6rjweqh8n?tab=Transactions
https://explorer.shimmer.network/shimmer/addr/smr1qzayrr9r0a4xvlu98u04f4ac0zfgt9q2wv8dm3cl4szdmn8hshmkvftv5pj
https://explorer.shimmer.network/shimmer/output/0x2efdebb745e1ecc3e6a24ccd20b919fed11fe10697982f15f156c1868686f9040000
https://explorer.shimmer.network/shimmer/output/0xe2c73230c07068ecd206c4c9a0490f9460dfc058dd93481a3d6f1c8251c2cdb00000
https://explorer.shimmer.network/shimmer/addr/smr1qzayrr9r0a4xvlu98u04f4ac0zfgt9q2wv8dm3cl4szdmn8hshmkvftv5pj?tab=Nfts

**Desktop (please complete the following information):**
 - OS: windows 11 home
 - Browser [EDGE]

**Comment by Ruben8897** [comment]
> Sorry, what this have to do with Soonaverse? You're just sending those NFTs between TanglePay and Soonaverse right? I'm sorry I'm little confused what you're doing.

Hi, I sent my nft to soonaverse (to the address soonaverse gave me to upload it to my soonaverse account) but it never arrived and I have no idea where it is or how to retrieve it. I am sure that I copied the shipping address correctly, the counter reached 0 and soonaverse did not recognize the nft. I did the process a few days later with another nft and everything went smoothly but the nft yun52 never arrived to soonaverse

**Comment by adamunchained** [comment]
> > Sorry, what this have to do with Soonaverse? You're just sending those NFTs between TanglePay and Soonaverse right? I'm sorry I'm little confused what you're doing.
> 
> Hi, I sent my nft to soonaverse (to the address soonaverse gave me to upload it to my soonaverse account) but it never arrived and I have no idea where it is or how to retrieve it. I am sure that I copied the shipping address correctly, the counter reached 0 and soonaverse did not recognize the nft. I did the process a few days later with another nft and everything went smoothly but the nft yun52 never arrived to soonaverse

I see, what was the address you sent it too and the NFT id?

**Comment by Ruben8897** [comment]
> > > Sorry, what this have to do with Soonaverse? You're just sending those NFTs between TanglePay and Soonaverse right? I'm sorry I'm little confused what you're doing.
> > 
> > 
> > Hi, I sent my nft to soonaverse (to the address soonaverse gave me to upload it to my soonaverse account) but it never arrived and I have no idea where it is or how to retrieve it. I am sure that I copied the shipping address correctly, the counter reached 0 and soonaverse did not recognize the nft. I did the process a few days later with another nft and everything went smoothly but the nft yun52 never arrived to soonaverse
> 
> I see, what was the address you sent it to and the NFT id?


sorry for the delay, I work at night and sleep during the day,

YES, the NFT is this #YUN52 the ID i think is this 
       0xbdad0ba457c164adb62bacc65330d20148ed8541710b77cc2052c41b96f177f7

https://explorer.shimmer.network/shimmer/addr/smr1zz766zay2lqkftdk9wkvv5es6gq53mv9g9cska7vypfvgxuk79mlwdwkurp      


the address I sent the NFT to I don't know exactly but the transaction is this 

https://explorer.shimmer.network/shimmer/transaction/0x21dded17a14c6073393439e477007c8fdd43c4bf069fcdcaf501bbe397a63d7a

this was not recorded in the movements of soonaverse's account, there is no record of the entry or arrival of the NFT #YUN52.**

**Comment by adamunchained** [comment]
> > > > Sorry, what this have to do with Soonaverse? You're just sending those NFTs between TanglePay and Soonaverse right? I'm sorry I'm little confused what you're doing.
> > > 
> > > 
> > > Hi, I sent my nft to soonaverse (to the address soonaverse gave me to upload it to my soonaverse account) but it never arrived and I have no idea where it is or how to retrieve it. I am sure that I copied the shipping address correctly, the counter reached 0 and soonaverse did not recognize the nft. I did the process a few days later with another nft and everything went smoothly but the nft yun52 never arrived to soonaverse
> > 
> > 
> > I see, what was the address you sent it to and the NFT id?
> 
> sorry for the delay, I work at night and sleep during the day,
> 
> YES, the NFT is this #YUN52 the ID i think is this 0xbdad0ba457c164adb62bacc65330d20148ed8541710b77cc2052c41b96f177f7
> 
> https://explorer.shimmer.network/shimmer/addr/smr1zz766zay2lqkftdk9wkvv5es6gq53mv9g9cska7vypfvgxuk79mlwdwkurp
> 
> the address I sent the NFT to I don't know exactly but the transaction is this
> 
> https://explorer.shimmer.network/shimmer/transaction/0x21dded17a14c6073393439e477007c8fdd43c4bf069fcdcaf501bbe397a63d7a
> 
> this was not recorded in the movements of soonaverse's account, there is no record of the entry or arrival of the NFT #YUN52.**
> 
> thank you for your time,
> 
> i repeat again that i put my hand in the fire that i copied the address that soonaverse gave me to receive the NFT in my soonaverse account, I hope it can be solved, thank you very much

NFT has been deposited, see NFT: https://soonaverse.com/nft/0xb7558cb1ccd2a1c50bfba96fbb21aec2eceb9f884fdc056f3526ba63960beeb7

Its under user: https://soonaverse.com/member/0xb301e89f046091a647a036bb902cbf1afc64ba52/nfts

**Comment by Ruben8897** [comment]
> > > > > Sorry, what this have to do with Soonaverse? You're just sending those NFTs between TanglePay and Soonaverse right? I'm sorry I'm little confused what you're doing.
> > > > 
> > > > 
> > > > Hi, I sent my nft to soonaverse (to the address soonaverse gave me to upload it to my soonaverse account) but it never arrived and I have no idea where it is or how to retrieve it. I am sure that I copied the shipping address correctly, the counter reached 0 and soonaverse did not recognize the nft. I did the process a few days later with another nft and everything went smoothly but the nft yun52 never arrived to soonaverse
> > > 
> > > 
> > > I see, what was the address you sent it to and the NFT id?
> > 
> > 
> > sorry for the delay, I work at night and sleep during the day,
> > YES, the NFT is this #YUN52 the ID i think is this 0xbdad0ba457c164adb62bacc65330d20148ed8541710b77cc2052c41b96f177f7
> > https://explorer.shimmer.network/shimmer/addr/smr1zz766zay2lqkftdk9wkvv5es6gq53mv9g9cska7vypfvgxuk79mlwdwkurp
> > the address I sent the NFT to I don't know exactly but the transaction is this
> > https://explorer.shimmer.network/shimmer/transaction/0x21dded17a14c6073393439e477007c8fdd43c4bf069fcdcaf501bbe397a63d7a
> > this was not recorded in the movements of soonaverse's account, there is no record of the entry or arrival of the NFT #YUN52.**
> > thank you for your time,
> > i repeat again that i put my hand in the fire that i copied the address that soonaverse gave me to receive the NFT in my soonaverse account, I hope it can be solved, thank you very much
> 
> NFT has been deposited, see NFT: https://soonaverse.com/nft/0xb7558cb1ccd2a1c50bfba96fbb21aec2eceb9f884fdc056f3526ba63960beeb7
> 
> Its under user: https://soonaverse.com/member/0xb301e89f046091a647a036bb902cbf1afc64ba52/nfts

no Adam , note that this is NAGA#57, I am talking about YUN#52.  With Naga I didn't have any problem, besides I have told you before that the other soonaverse sendings and withdrawals that I have made from various accounts have gone well

**Comment by Ruben8897** [comment]
![image](https://github.com/soonaverse/app/assets/114197646/7f1bdf35-0729-4785-91da-31c153a4e62c)
  

here i talk about naga nft

**Comment by adamunchained** [comment]
> ![image](https://private-user-images.githubusercontent.com/114197646/297499882-7f1bdf35-0729-4785-91da-31c153a4e62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MjEzMjksIm5iZiI6MTcwNTUyMTAyOSwicGF0aCI6Ii8xMTQxOTc2NDYvMjk3NDk5ODgyLTdmMWJkZjM1LTA3MjktNDc4NS05MWRhLTMxYzE1M2E0ZTYyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxOTUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTgxZTNmZDUzZDEzOTQ5Nzg3NGIwZTM2MTE4MDI1NjEwNzYwOGUwYjQzNTIzNWVhNjNlZGExZjUyYWMwNDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PnNY624mR8KgkIc8PHMAZAr0OR2Y0d2AynNTvbTRV5A)
> 
> here i talk about naga nft

You said it’s this transaction: https://explorer.shimmer.network/shimmer/transaction/0x21dded17a14c6073393439e477007c8fdd43c4bf069fcdcaf501bbe397a63d7a

Above transaction links to NAGA#57. Can you provide transactions for YUN#52?

**Comment by Ruben8897** [comment]
> > ![image](https://private-user-images.githubusercontent.com/114197646/297499882-7f1bdf35-0729-4785-91da-31c153a4e62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MjEzMjksIm5iZiI6MTcwNTUyMTAyOSwicGF0aCI6Ii8xMTQxOTc2NDYvMjk3NDk5ODgyLTdmMWJkZjM1LTA3MjktNDc4NS05MWRhLTMxYzE1M2E0ZTYyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxOTUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTgxZTNmZDUzZDEzOTQ5Nzg3NGIwZTM2MTE4MDI1NjEwNzYwOGUwYjQzNTIzNWVhNjNlZGExZjUyYWMwNDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PnNY624mR8KgkIc8PHMAZAr0OR2Y0d2AynNTvbTRV5A)
> > here i talk about naga nft
> 
> You said it’s this transaction: https://explorer.shimmer.network/shimmer/transaction/0x21dded17a14c6073393439e477007c8fdd43c4bf069fcdcaf501bbe397a63d7a
> 
> Above transaction links to NAGA#57. Can you provide transactions for YUN#52?

sorry Adam i have a mistake

transacction:
https://explorer.shimmer.network/shimmer/transaction/0xe2c73230c07068ecd206c4c9a0490f9460dfc058dd93481a3d6f1c8251c2cdb0

ID YUN#52    0xbdad0ba457c164adb62bacc65330d20148ed8541710b77cc2052c41b96f177f7

https://explorer.shimmer.network/shimmer/addr/smr1zz766zay2lqkftdk9wkvv5es6gq53mv9g9cska7vypfvgxuk79mlwdwkurp

**Comment by adamunchained** [comment]
This has been fixed. Your NFT got stuck due delays on the network back in Dec 17.

Your NFT should be refunded back to you. You can deposit it again and it should work this time.
