### ISSUE TITLE
Attempted deposit of NFT remains on soonaverse deposit address

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#103]
**Describe the bug**
User attempted to deposit NFT onto soonaverse from a new and unrecognized collection (GroupFi Alpha Testers NFT).  Soonaverse generated deposit address was: smr1qzyed3854kjq9r30t7nzt353afynhnmrcxng3psytj6ecd0x4rus69d07hl

Review of explorer appears as though the NFT remains on that deposit address and user claims there is nothing listed under the transactions tab of soonaverse profile.

NFT address: smr1zz5z7mklnauvq3yvjq7da2z6mx268x5e7s5ar52kke26t30uuq4g2qj0u3f
NFT ID: 0xa82f6edf9f78c0448c903cdea85ad995a39a99f429d1d156b655a5c5fce02a85
Soonaverse member ID: 0x373e9524907354fa49729726174254bc0a0f835c
Discord: Bug Issue-495

![image](https://github.com/soonaverse/app/assets/112674501/f98d5905-721f-4d1e-97c5-84f2aa936f69)

**Comment by flyingrabbit-lab** [comment]
The NFT has been sent back to you. Please retry the deposit
