### ISSUE TITLE
(Shimmer OG) NFT Deposit remains on soonaverse deposit address, not visible in Account

### ISSUE THREAD

**Issue by r4ggons** [soonaverse/app#104]
**Describe the bug**
I attempted to deposit one Shimmer OG NFT onto soonaverse. 
Soonaverse generated deposit address was: smr1qzycm5ez6vq7pzy05e9wuxcc75rleekf83py5p32tmxw69372hpp2vc2hz3
NFT is on the receiving address now but not visible on my profile, Transaction in Soonaverse was not recognized. 

**Expected behavior**
NFT appearing in my account, transaction is visible in my account

**Screenshots**
![imade](https://github.com/soonaverse/app/assets/133001868/35b66a73-3e8b-45b6-ac8b-e9269ed7b0b0)
![222](https://github.com/soonaverse/app/assets/133001868/41ec5556-1f4d-4034-bf08-698a6780dea3)
![image](https://github.com/soonaverse/app/assets/133001868/2b30a25e-168f-4123-9fbc-1494d3c11b5a)

**Additional context**
Storage Deposit was gifted.
My SMR sending address: smr1qrh2tm9ynsu67r824asjel9zfse3u3npy5vxjp2ddq5knwypw078vpgk90l
Receiving SMR address: smr1qzycm5ez6vq7pzy05e9wuxcc75rleekf83py5p32tmxw69372hpp2vc2hz3
Soonaverse Acc: 0x45f4E16B0284698A63E12317bC3c5B05678C20b5

**Comment by flyingrabbit-lab** [comment]
The NFT has been sent back to this address: smr1qrh2tm9ynsu67r824asjel9zfse3u3npy5vxjp2ddq5knwypw078vpgk90l
Please try depositing it again.
