### ISSUE TITLE
Losted $Fuel on transfer for soonaverse sell order

### ISSUE THREAD

**Issue by tomstrug** [soonaverse/app#105]
Hi! Happy new year!

![Capture2](https://github.com/soonaverse/app/assets/133142111/cd1cf59b-3c7a-4197-a04c-eb0cacc037ed)
![Capture](https://github.com/soonaverse/app/assets/133142111/f6835904-8435-4fc5-9137-d4a68a1051c5)

I placed a sell order to sell 160,000 FUEL for SMR.  
But I received SMR for 80,000 and the rest is no longer active on the order book.
smr1qzw8lcawp7rk3wleaw0muzk5pvdg8rpydsvveuwdy3r4gj9haywmgcpa2dz
 is the address to which I sent the $fuel and half of it was lost.

**Comment by tomstrug** [comment]
![Capture3](https://github.com/soonaverse/app/assets/133142111/c0d80d45-81b8-4440-acde-087054d65b91)

**Comment by flyingrabbit-lab** [comment]
I have checked this and I see a sell order for 160 000 FUEL and 4 payments to this address:
smr1qqt58w88c5eeclldp7tq8shq3t7pgy38j0k9hfx9y86qa6p40zadjy6hkce
This your address, right?

https://explorer.shimmer.network/shimmer/block/0x7637811887d5a8f754b06b3c481dc18304bd173df4e9013840a7cc9c7581379d
https://explorer.shimmer.network/shimmer/block/0xb748ab69e5f0ec7a33b2f7d7bc420f3e9670141389c6f1897596bfe0d9686b54
https://explorer.shimmer.network/shimmer/block/0xeb5868eb4aa5cb8814ea3c4ba4caada82df7c782bd0a6258f873a8d3d42d4c5d
https://explorer.shimmer.network/shimmer/block/0x31953938312eefe33fe123d3cdbb211f98fc61db78dcbb7a76747a3076aa5026

**Comment by tomstrug** [comment]
Yes, it's mine. But I have received the half of the SMR of my order...

**Comment by flyingrabbit-lab** [comment]
You have created a sell order, 160 000 FUEL, price 0.005.
You should have received minimum 800 SMR
The four transactions sent total of 823.77 SMR to you.
Aren't these correct numbers?

**Comment by tomstrug** [comment]
Good morning,
I don't understand: on my wallet, I did not receive my entire sale: here is the receipt of SMR for my transaction.
![Capture10](https://github.com/soonaverse/app/assets/133142111/9005616d-a1b6-4d97-83e0-4f12185ecc63)

**Comment by tomstrug** [comment]
I just sent 160000 fuel for a sale action and here are my transactions on firefly.

**Comment by adamunchained** [comment]
> I just sent 160000 fuel for a sale action and here are my transactions on firefly. Strange or not?

This seems to be a Firefly issue, we can clearly see on the ledger that total of **823.77 SMR** has been settled to smr1qqt58w88c5eeclldp7tq8shq3t7pgy38j0k9hfx9y86qa6p40zadjy6hkce , see below transactions:


- https://explorer.shimmer.network/shimmer/block/0x7637811887d5a8f754b06b3c481dc18304bd173df4e9013840a7cc9c7581379d - **423.94 SMR**
- https://explorer.shimmer.network/shimmer/block/0xb748ab69e5f0ec7a33b2f7d7bc420f3e9670141389c6f1897596bfe0d9686b54 - **8.41 SMR**
- https://explorer.shimmer.network/shimmer/block/0xeb5868eb4aa5cb8814ea3c4ba4caada82df7c782bd0a6258f873a8d3d42d4c5d - **99.94 SMR**
- https://explorer.shimmer.network/shimmer/block/0x31953938312eefe33fe123d3cdbb211f98fc61db78dcbb7a76747a3076aa5026 - **291.48 SMR**

Please reach out to Firefly team to check why you don't see the balance in your wallet.

**Comment by tomstrug** [comment]
Ok perfect. Thanks a lot!
