### ISSUE TITLE
NFT blocked on soonaverse adress

### ISSUE THREAD

**Issue by tomstrug** [soonaverse/app#106]
Hi friend!
Sorry, I forgot the gift storage deposit for a pharaoh nft transfert to soonaverse...He is stuck now.

Here's the adress where my nft is blocked:
smr1qrp52fysck03k40zew04tzhvkpny8g7e0wyxy79vklzuvxju87nw7ah4gjn

Here's my send shimmer adress:
smr1qqt58w88c5eeclldp7tq8shq3t7pgy38j0k9hfx9y86qa6p40zadjy6hkce

Thank you so much!

**Comment by tomstrug** [comment]
And I have some $GCT bloked on this adress too for the same oversight ...
smr1qqqcuewfpyyn5tta07th096egnjf5fcgyjurrqwma6yrydujfmphk08vn4k

![Capture4](https://github.com/soonaverse/app/assets/133142111/92c2b7d5-34da-4804-a848-439624834873)

**Comment by flyingrabbit-lab** [comment]
$GCT seems to me that it was sent back. Could you confirm?

**Comment by flyingrabbit-lab** [comment]
Regarding the NFT, you should have an option to claim it back.

@adamunchained The credit transaction (0xd8ac23ceac0efd4d3490f7e69cb198dc88ed744e) was created in November. If I know correctly pagination is not working properly on transactions page, so the user won't be able to claim the stuck NFT.

**Comment by tomstrug** [comment]
Yes that's right. My GCTs came back :)

**Comment by tomstrug** [comment]
I can't claim my NFT back: there is no trace on my firefly of this transaction...

**Comment by adamunchained** [comment]
> Regarding the NFT, you should have an option to claim it back.
> 
> @adamunchained The credit transaction (0xd8ac23ceac0efd4d3490f7e69cb198dc88ed744e) was created in November. If I know correctly pagination is not working properly on transactions page, so the user won't be able to claim the stuck NFT.

leave it with me, I'll investigate this tmr

**Comment by tomstrug** [comment]
@adamunchained Hi friend! Did you find a solution for my nft stuck on this soonaverse address plz?

**Comment by tomstrug** [comment]
I'm sad, I have no way to claim it back...

**Comment by iotaflea** [comment]
@adamunchained user still inquring whether NFT is recoverable

**Comment by whatmicha** [comment]
@adamunchained please do sth
