### ISSUE TITLE
Improve front-end ERROR message to tell user they don't have validated address on their profile

### ISSUE THREAD

**Issue by ecococohub** [soonaverse/app#107]
I've transferred an NFT (Shimmer OG NFT #1233) 
from my wallet Shimmer to Soonaverse and now I have this message **"Failed due internal error"** every time I trying to sell 
 or withdraw it when I press Confirm Listing or Withdraw NFT then will pop up this **Failed due internal error.**
![image](https://github.com/soonaverse/app/assets/155842855/de511348-6bbd-466a-8f59-ba6eab151585)

Using browser :

Brave is up to date
[Version 1.61.114 Chromium: 120.0.6099.199 (Official Build) (64-bit)](https://brave.com/latest/)

OS :
Edition	Windows 10 Pro
Version	22H2
Installed on	‎10/‎12/‎2020
OS build	19045.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by flyingrabbit-lab** [comment]
You can not withdraw it as you don't have a validated smr address.
Validate your smr address and it should work.

**Comment by flyingrabbit-lab** [comment]
@adamunchained Soonaverse should be updated to show the actual error

**Comment by ecococohub** [comment]
Great! its working now Thank you. 
Just let you know that still showing the same old message, I just tested today, before I validated my address.
