### ISSUE TITLE
Minting to network stuck. 

### ISSUE THREAD

**Issue by Al-Birch** [soonaverse/app#108]
Hello. 
I minted a collection of 6100. I then tried transferring to network and it has been stick at 5872 NFTs for four days. It is Tribal Lodges NFT Collection. https://soonaverse.com/nft/0xe866a59f286463587567e22020e000f5615cf2aa
![IMG_4560](https://github.com/soonaverse/app/assets/94172760/1bcf9444-e44e-41e1-91d2-ea6e63f7b764)

**Comment by Al-Birch** [comment]
This is when I have tried to move onto the decentralised network after I have already minted on soonaverse.

**Comment by Al-Birch** [comment]
Do we think this is going to result in the whole collection being lost?

**Comment by Al-Birch** [comment]
Does this now mean someone is looking at it? Thanks.

**Comment by flyingrabbit-lab** [comment]
> Does this now mean someone is looking at it? Thanks.

Yes, I am taking a look now.

**Comment by Al-Birch** [comment]
Hey Bud. Thank you.

**Comment by Al-Birch** [comment]
Is it fixable?

**Comment by Al-Birch** [comment]
No worries. Thanks just hoping it's not all lost.

**Comment by flyingrabbit-lab** [comment]
Don't worry, nothing is lost. Minting is currently in progress, it is just slow due to the size and the amount of the NFTs.

**Comment by whatmicha** [comment]
I think actually it is "stuck" since several days with that amount of NFTs left - not sure if it is related to size and amount of NFTs anymore?

**Comment by adamunchained** [comment]
> Can it be fixed?

Of course it can, just please be patient with us. There are many variables that goes into the minting and it can get very complex with various collections.

**Comment by Al-Birch** [comment]
No worries, Adam. Thanks to all. Al

**Comment by flyingrabbit-lab** [comment]
I am happy to let you all know that the collection has been minted. Apologies for the delay, we had some unforeseen issues. If you need help with anything else feel free to let me know.

**Comment by Al-Birch** [comment]
Thank you. Hope it wasn't too much trouble for you.

**Comment by adamunchained** [comment]
Great effort @flyingrabbit-lab, thank you for fixing this!
