### ISSUE TITLE
OG shimmer NFT problem receive to soonacerse 

### ISSUE THREAD

**Issue by Young195** [soonaverse/app#111]
Soonaverse does not receive the and nft shimmer

I wanted to send my og shimmer nft which was in my firefly shimmer, to put it on Soonaverse
I made an nft deposit request, Soonaverse gave me an address
I took this address, and send my nft to this address
Deposit for gift storage ok
Nothing appears on my Soonaverse profile, whether the transaction or the nft
The devs seem aware but apparently nothing alarming because we haven't responded to the message on the discord for several days

**Comment by adamunchained** [comment]
Could you provide the address you used? Do you have a validated address on your member profile?

**Comment by adamunchained** [comment]
Im closing this since I din't get any response. Feel free to re-open if this still an issue.
