### ISSUE TITLE
Mint & Claim issues - No data loaded - Soonaverse doesn't work

### ISSUE THREAD

**Issue by LordSciFi** [soonaverse/app#112]
**Describe the bug**
The content of the soonaverse is not loaded. Neither on the profile page nor on NFT detail pages.
If the content/data loads it takes ages.
Purchase or claim process can't be executed since something will fail. 

**To Reproduce**
1. Go to Soonaverse.com
2. Click on "My Profile"
3. Go to the tab "Activity" and try to claim your weekly rewards
4. See error - Nothing is lodaing and if the rewards are loaded they can't be claimed. Same is for purchasing NFTs as i understand.

**Expected behavior**
I should be able to claim my reward and mint NFTs.

**Screenshots**
![Profile1](https://github.com/soonaverse/app/assets/79095057/4264c041-c49f-4ede-9d89-98d748ad11e7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 120.0.6099.217 

**Smartphone (please complete the following information):**

**Additional context**
![NFT minting](https://github.com/soonaverse/app/assets/79095057/dd4b15d8-8afb-4498-a312-6400aec8286c)
![Ooops SOON](https://github.com/soonaverse/app/assets/79095057/7ffa9c25-7075-438e-8fe1-e5ed3026f36c)

**Comment by LordSciFi** [comment]
Additionally one can't edit spaces. Just wanted to edit one of my old spaces and there was a message "Failed". Somehow it created a proposal and i'm the only guardian in that space but it failed. Also i'm logged in (can see the VIP level and profile image), it also lists 1 Guardian for the space but it's just blank instead of showing my account as guardian.

**Comment by adamunchained** [comment]
what user and space is this? I've edited a space without an issue and also loaded member.

**Comment by adamunchained** [comment]
<img width="1833" alt="Screenshot 2024-01-16 at 10 10 41 AM" src="https://github.com/soonaverse/app/assets/130610/658b61db-44cc-482d-a60f-2cfb5740925f">

I'm able to load the page. Can you open your developer console and see if there are any issues?

**Comment by adamunchained** [comment]
Is this still happening to you? I'm unable to replicate this.
