### ISSUE TITLE
B5: Bulk Transfer

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/app#115]
- enable ability to perform bulk transfer of NFTs (owner change for NFTs on the platform)
- make sure auditable transaction is recorded about the transfer

**Comment by flyingrabbit-lab** [comment]
@adamunchained Just to clarify, this should work with NFTs that are already on B5?

**Comment by adamunchained** [comment]
> @adamunchained Just to clarify, this should work with NFTs that are already on B5? So input param can be a list of nftId targetAddress pair?

yes only NFTs that are deposited within the platform.

**Comment by flyingrabbit-lab** [comment]
We need a target where to send the NFT. Should it be rather member id? 
Does the NFT has to stay within the platform or bulk transfer can send it anywhere?

**Comment by adamunchained** [comment]
released to prod
