### ISSUE TITLE
Soonaverse token

### ISSUE THREAD

**Issue by d3r-schosch** [soonaverse/app#117]
**Describe the bug**
![grafik](https://github.com/soonaverse/app/assets/140895265/5abeecc4-07ac-429d-b555-78e17eac74bb)

Selling is not triggered at 2.55 although buy order is way higher 2.962

**Comment by adamunchained** [comment]
@flyingrabbit-lab - this should not happen anymore right because we don't have min amount on the Stardust.

**Comment by flyingrabbit-lab** [comment]
Currently the order book look correct to me
<img width="463" alt="image" src="https://github.com/soonaverse/app/assets/109557696/41d91cfb-3db0-4e8a-a5cd-27a7f08d8bbd">

**Comment by adamunchained** [comment]
It must have been a delay on clearing then. We will investigate if it happens again.
