### ISSUE TITLE
Upload Banner NFT Collection Soonaverse

### ISSUE THREAD

**Issue by dither24** [soonaverse/app#119]
When i drag a photo in the upload field for a banner, it never upload. It get stuck in "uploading". Everything is still working. 

1. Go to 'Create new'
2. Click on 'Collection'
3. Scroll down to 'Banner'
4. Upload the jpeg in 2350x1080
5. See error (uploading)

**Expected behavior**
A finished upload of the banner after a few seconds.

Desktop: iMac
 - OS: Catalina 10.15.7
 - Brave Browser
 - v 1.61.120

I tried different types, like jpeg or png. With the uploading of an Avatar photo in "Creatin a new space", is the same issue. Tried also in Google Chrome, it still don't work.

![Banner_Uploading_error](https://github.com/soonaverse/app/assets/157412931/bbfbf6b2-1869-4901-8c7a-58683efc0033)

**Comment by adamunchained** [comment]
This has been fixed. Please try again.
