### ISSUE TITLE
Implement GroupFi into Soonaverse

### ISSUE THREAD

**Issue by LordSciFi** [soonaverse/app#121]
**Is your feature request related to a problem? Please describe.**
Soonaverse is not social, currently. We need to make the Soonaverse social either with a web2 or web3 communication SDK. Of course, I'd prefer to have "Web3-based communication".

**Describe the solution you'd like**
GroupFi has a working product for Web3-based chats, the text messages are stored in the transactions message on the SMR protocol. 

**Describe alternatives you've considered**
Implementing a web2 SDK until we can implement a web3 communication SDK.

**Additional context**
There are several things we discussed:
1. We want to implement the GroupFi chat to be available on the entire site (like a chat on Facebook or LinkedIn), before the 23rd of February
2. We would like to implement a "news feed" on the spaces this might require GroupFi to change/configure some parts of their product to make this happen
3. Last thing we discussed in terms of GroupFi is that we would also like to have a "forum section" on the spaces blueprint so space members can discuss topics related to the space

This will be implemented by the developers of GroupFi hence I created the Github Issue so we can keep talking about it here and also coordinate the implementation (if help is needed). 

Note: Currently GroupFi only works with the Tanglepay wallet but the MetaMask wallet and others will follow.

**Comment by SoonaverseTF** [comment]
Test
