### ISSUE TITLE
Deposit NFT Failure - NFT remains on soonaverse-generated deposit address

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#129]
**Describe the bug**
Discord Ticket: community-522
Shimmer OG NFT was attempted to be deposited to soonaverse but was never completed.  NFT remains on soonaverse-generated deposit address.

Soonaverse deposit address with NFT: smr1qqafmudxknzd0cc2eyvwp3m7t795d8rkdsacpd0ug3rsjesh6v6cyr7lwzx
Transaction ID: 0x5bba615d3b2b3e3a0ce65e1865be9f3de4e5c88c7d9fdf505c7c840ebeb3048d
Soonaverse member ID: 0x8821bcbbba477f9390e31500d41740cb64f9145d
NFT address: smr1zrvxdgy2tmcq4krsaskvpjpskla564g3nv252d8kqplrxhw4x34dvr77tpu

**Comment by flyingrabbit-lab** [comment]
Nft has been credited back.
