### ISSUE TITLE
failure in the stake, bugissue-479

### ISSUE THREAD

**Issue by x3ltor** [soonaverse/app#130]
I sent from my wallet BLOOM 968.19 $SOON on December 3, 2023 with a week of staking, in the transfer I had the error or the wallet automatically assigned me an expiration time, outside of the assigned time, a timelock of one week.
![soonaverse1](https://github.com/soonaverse/app/assets/95258613/080dab27-340d-47d1-b716-9e5cee595339)
There was no event, nor did it report on the staking list, after a week nothing happened.
![soonaverse5](https://github.com/soonaverse/app/assets/95258613/5691b468-52df-4d7e-bf5e-9a6f63e6407e)
I couldn't claim my tokens,
![soonaverse4](https://github.com/soonaverse/app/assets/95258613/94bdc577-6283-4aaf-9bd2-2be1cc28090d)
it's in one of your wallets, waiting for it to be claimed, because I think it was my mistake when sending the tokens, I shouldn't have assign expiration time, or timelock for a week
![pantallazo](https://github.com/soonaverse/app/assets/95258613/e6d16e84-a4e7-429d-9ab2-b43f9e0a69d3)

**Comment by adamunchained** [comment]
Could you hover over the "date" for that transaction line in the list and provide us with ID?

**Comment by x3ltor** [comment]
uid: 0x294f048a196951086772c12bf11c1aae5b264856, tries: 0
![soonaverse6](https://github.com/soonaverse/app/assets/95258613/65a21f0e-41fc-4a0a-b1d5-5a3d4092f456)

**Comment by adamunchained** [comment]
Are you able to open developer console in the browser then hit the "confirm and generate address"? See console tab. Take screenshot of any error in there. You might be able to see more explanatory error to help us identify the issue. 

See this help for developer console: https://support.google.com/campaignmanager/answer/2828688?hl=en#:~:text=Right%2Dclick%20a%20page%20and,View%20%3E%20Developer%20%3E%20Developer%20tools.

**Comment by x3ltor** [comment]
![soonaverse7](https://github.com/soonaverse/app/assets/95258613/7d077a5c-c294-4e42-a1cb-7b9e27272762)
after pressing " confirm and generate address"
![soonaverse8](https://github.com/soonaverse/app/assets/95258613/732c2ebb-bee3-435a-88cf-322a9d6236ba)

**Comment by x3ltor** [comment]
Can you please confirm if the screenshot is correct?

**Comment by x3ltor** [comment]
Hello, I want to know the situation of my problem, also the same thing happens to me again today, I have 24 $soon tokens in one of your wallets, I can't claim them, same problems.

**Comment by x3ltor** [comment]
![image](https://github.com/soonaverse/app/assets/95258613/a45c6d31-5a89-4c61-a8be-5f084fd35409)

**Comment by x3ltor** [comment]
![image](https://github.com/soonaverse/app/assets/95258613/4f963280-fd74-4651-9d5c-47619c4cf188)

![image](https://github.com/soonaverse/app/assets/95258613/2213d6d0-8d57-4f80-9b5b-a2c11f62b671)
