### ISSUE TITLE
Wrong browser tab labels

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/app#143]
**Describe the bug**
Hi dear Code Magicians :)

At first I saw this as kind of accidental nano-leak but now I think it's only a small bug that can be reproduced with the following 2 sets of steps:

**Reproduction (1) - Permanent wrong label**
1. Using OG World to check NFT marketplace (https://ogw.iota.love/radar/epochzero)
2. Click on any of the NFT-Addresses (opens for example the URL https://soonaverse.com/nft/0x5dff0c7bde3cb86ed2717b6a55f95aecedad6bd0)
![image](https://github.com/soonaverse/app/assets/104099536/4e9ca5cb-0d17-4143-8784-4f3633e2895d)

3. This opens a new browser tab of Soonaverse but the browser tab is labled "BUILD.5" instead of "Soonaverse"
4. Since most of the EpochZero NFTs seem to have been withdrawn, the link points into nirvana and the site stays on "Oops, it's in another universe" with the wrong tab label
![image](https://github.com/soonaverse/app/assets/104099536/fdb4a2ca-9048-438f-9fc3-c52000c5a9c3)

**Reproduction (2) - Temporary wrong label**
1. First visit any collection or profile with a bunch of NFTs. In case of a profile, go to its NFT tab. 
--> Soonanaut collection in this example: https://soonaverse.com/collection/0xcbe28532602d67eec7c937c0037509d426f38223
2. Then click on the "S-shaped homebutton" in the top left corner leading to soonaverse homepage
3. From there "go back" in ur browser
![image](https://github.com/soonaverse/app/assets/104099536/da1935e4-1f57-469c-91f2-e951e41fa7e6)

4. During the loading of the NFTs of collection chosen in Step 1 the browser tab label is "BUILD.5" until NFTs are finished loading
![image](https://github.com/soonaverse/app/assets/104099536/ac6cf888-8e70-422c-aa88-c38c4086ef39)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 123.0.1 (64-bit)

As mentioned in the intro, this isn't something severe. Just wanted to let u know.

Cheers
Bananu

**Comment by emmap3-do** [comment]
If you visit any page in the Soonaverse website and do a hard refresh, you will see the BUILD.5 title for a second. So it seems it's like a default value that gets overwritten later when the page is loaded.

**Comment by CptBananu** [comment]
Well then I'll close this. Simply didn't realize this before :)

**Comment by emmap3-do** [comment]
Well, I'm not sure if it's a bug or by design.
