### ISSUE TITLE
Delist all Daobee NFT collections

### ISSUE THREAD

**Issue by LinusNau** [soonaverse/app#146]
Hello Soonaverse Team,

I want to ask you to delist all Daobee NFT collections from sales:
Daobee Family (https://soonaverse.com/collection/0x9b996f998833ae98d155a83cc67c16514a9e5b0c)
Golden Daobee (https://soonaverse.com/collection/0x519ccc6046083ec07132951ccab0e571777449de)
Promo Daobee Coin Giveaway (https://soonaverse.com/collection/0x454fe8b9d5320ef576d482143a41f77e5e505113)

And also remove the Daobee IOTA addresses from receiving secondary sale royalties (secondary sales can go on, but no royalties should be forwarded to our addresses).
- Address for NFT sale income: iota1qqld4t292spq6wjpuljsewc0c956vejve7wrrn304kmzprxezvkvzgrx5f8
- Address for royalties: iota1qrl7599y44eca9yqcmxexp0g6438jnjrlraa4q7ergvpnv0acx0zw84p6jd

This is necessary, as we stop operating our German legal wraper, which must include stopping sales operations and income.

Thanks for your support,
Linus

**Comment by centercirclesolutions** [comment]
This has been completed. Please verify @LinusNau
