### ISSUE TITLE
Add Warpcast to social links of Soonaverse profiles

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/app#147]
Hi frens :)

Would be cool if we could link our Warpcast profile in the Social tab of our Soonaverse profiles (similar to X, Discord, Github)
Especially after yesterdays awesome AMA pointing out the benefits of Warpcast :)

Thx in advance and cheers,
Bananu

**Comment by emmap3-do** [comment]
@adamunchained could you please add a new property for the warpcast/farcaster user handle in the backend, so we can add it later to the frontend?

**Comment by adamunchained** [comment]
@flyingrabbit-lab - could you do a quick hotfix on this please? Ability to store warpcast profile ID on member.
