### ISSUE TITLE
NFT withdrawal does not work

### ISSUE THREAD

**Issue by rodion222222** [soonaverse/app#149]
Several unsuccessful attempts to withdraw NFTs to the wallet. IOTA network.

I am attaching the explorer data:
https://explorer.iota.org/mainnet/block/0xa202f03bdeb461db3d3acfeebcbac2e5cd101d5c933c28c443fc2a7107a2253c

https://explorer.iota.org/mainnet/block/0xffffe560d2052e0df768fdfba6b36ebb8cb7971eb7f5af1be6920b82d1030dc7

https://explorer.iota.org/mainnet/block/0x81979b9910166d6f00ddb8f3621fc57cc7c71bddcab23a6e8dc56e9d5938a838

**Comment by adamunchained** [comment]
Let us finalize migration to PostgreSQL and once completed we will investigate. Migration to PostgreSQL is getting very close and we should be able to push it out within next two weeks.

**Comment by rodion222222** [comment]
Hello! It seems I managed to find the source of this error. Transactions are executed if the NFTs in the collection are purchased sequentially without applying a search. But if you buy an NFT through a search within the collection, a conflicting transaction appears when withdrawing the NFT.

**Comment by ChrBender** [comment]
@adamunchained 
I have the **same problem** with the following transactions, that are **conflicting**, too:

https://explorer.iota.org/mainnet/block/0x5f81bceabd8c12fd947807cdec10d98127d3cdde881be8d8ccba6e8acae32faa
https://explorer.iota.org/mainnet/block/0x02113f5af09b7e4a897465ccce24af8e34b2b1ed2fddd6f8473ccf743f93d9ef
https://explorer.iota.org/mainnet/block/0x937ab4315fef2ba2b86265297b0a5d793afd74d3ca833ec1c5d18157936a7eb1

**Comment by MrRo-de** [comment]
I tried to withdraw my NFT too, but I don't even get to this point. As soon as I confirm the warning I get the error message: "Failed due internal error."

**Comment by adamunchained** [comment]
should be fixed as part of the https://github.com/soonaverse/app/issues/182
