### ISSUE TITLE
User claims IOTA sent to soonaverse CEX and not completed for order

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#150]
User claims 5000 IOTA were sent as a sell order on Soonaverse but order is not registered on order book and remains on Soonaverse address.  Discord ticket 567

here below transaction ID and links

0x3c8d4d292286e8e54bc907651a016cc1d7713c62c9fe1f8efcc28d5b8a489dd2

https://explorer.iota.org/mainnet/transaction/0x3c8d4d292286e8e54bc907651a016cc1d7713c62c9fe1f8efcc28d5b8a489dd2

**Comment by centercirclesolutions** [comment]
@adamunchained is this anything I can help with?

**Comment by adamunchained** [comment]
@flyingrabbit-lab - can you check please? I can see there is an order / payment in the system with this address.

**Comment by flyingrabbit-lab** [comment]
The user's sell order was fulfilled on the 9th of May. I can see that they created the order earlier, but we were doing updates that time and it seems that the order was not picked up. Now everything should be okay.

**Comment by adamunchained** [comment]
thank you!
