### ISSUE TITLE
User revenue for sold NFT with pending conflicting transaction

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#151]
Soonaverse user: 0xce4e4adbc0834333baaa04e523ed8411507b08f3

User never received payment for selling his NFT on soonaverse.  In Shimmer explorer it reports as "conflicting"
https://explorer.shimmer.network/shimmer/block/0x5b9405a876e290cf38d55c69a296ff90a1623d4f9879ac897721fc0a395e0d8b

Appears as though NFT was purchased through bulk buying option with this transaction:
https://explorer.shimmer.network/shimmer/transaction/0xd0fe88b422be1ed270ceb4052964b4944cb4c1af4b2f01f2fb81b31e4afd8a8d

**Comment by iotaflea** [comment]
Can you please have a look @adamunchained

**Comment by flyingrabbit-lab** [comment]
Payment received
