### ISSUE TITLE
After migration NFT collection does not update with new owner of NFTs and internal errors

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#152]
If you look at NFT collection: https://soonaverse.com/collection/0x81a7845b52d0725c607c80a2c83d390334565b09

NFTs still remain for sale at floor and within prior owners soonaverse profile.  It appears as though Soonaverse captured the private sale but new owner cannot withdraw and receives error along the lines of "internal error".  NFTs do not appear in new owners profile.

New owner can change listing price... but collection and marketplace page does not change listing from prior owner and price.

NFTs:
https://soonaverse.com/nft/0xe99bbf557986fb652d53945e126a9506759899c9
https://soonaverse.com/nft/0xcf28154503e30f1746b6fa149cb9319a6bf844ee
https://soonaverse.com/nft/0xc496249d243ea5f7f79350abadb335961bcfb49f
https://soonaverse.com/nft/0xaccaf2f5312a1be15c12279f21dccce3b9203d2b
https://soonaverse.com/nft/0xfae5237883bc5616cf072978c3e382994cae8498
https://soonaverse.com/nft/0xa383b7085a93b1cef9b8dbcea69659bfe9d1550b
https://soonaverse.com/nft/0x659389f9c0a5a986059988b6b8ac3130f4e1dc26
https://soonaverse.com/nft/0x4cd5010ab6712192ae0ff59ab2a0feac0401773c
https://soonaverse.com/nft/0x41a1a1b29773545c67e6a740b71e6ec82626cd0d
https://soonaverse.com/nft/0x177750b22217fa81ec71e9a99fac38c0e7327eb3
https://soonaverse.com/nft/0x0b385a5a6a5baf5e8c0a1d61851de086c8dcf48d
https://soonaverse.com/nft/0x08eab96cf425feeeef3dbc0fe3391b2e8aa7606b

**Comment by emmap3-do** [comment]
@adamunchained this issue is related to what I mentioned today

**Comment by iotaflea** [comment]
I've also deposited numerous NFTs and it shows as success with correct owner.   But the NFTs cannot be found and are not within the user profile.

**Comment by emmap3-do** [comment]
If I got it right from @adamunchained , Soonaverse is using Algolia for some lists (eg. collection nft list, profile nft list) and it seems Algolia is not properly syncing the data for Soonaverse, hence some lists show old data.

Based on this, the issue @epochzro mentions is a separate one, because it's related to the usage of the API, which is returning 404 error on any requests. I've just tried a working request I had on Postman and it returns 404:
https://api.buildcore.io/api/getById?collection=member&uid=0x4bdea1ceb9f480d6116b3d12855554b382d33692

I've tried GET and POST verbs. I've tried with and without /api in the url, same response: 404 not found

Maybe there is something blocking by IP or something new that was added to the APIs and we're not aware?

**Comment by emmap3-do** [comment]
You're right. 

Minor thing, I tried that one you provided and returned an error saying setId is required. So, I replaced uid with setId and it worked: 
https://api.buildcore.io/search/getById?dataset=member&setId=0x4bdea1ceb9f480d6116b3d12855554b382d33692

**Comment by flyingrabbit-lab** [comment]
Algolia should be fixed now. Could you check and confirm please?

I am currently checking why getUpdatedAfter is not working.

**Comment by iotaflea** [comment]
Ok things seem to be moving forward.  Owners seem to now be updated. but the collection page now doesnt display listing prices or anything. 
![image](https://github.com/soonaverse/app/assets/112674501/b63b6b1e-a74c-452c-a918-df61becc86f4)

**Comment by flyingrabbit-lab** [comment]
Api is also fixed now

**Comment by flyingrabbit-lab** [comment]
Only that.

**Comment by flyingrabbit-lab** [comment]
Could you send me a transaction id?

**Comment by flyingrabbit-lab** [comment]
Not on payload.restrictions.

**Comment by iotaflea** [comment]
withdrew NFTs... then they disappear from soonaverse as normal, then later, they reappear in profile.  of course clicking on them, they return the normal error that they are in another universe but never seen that before where it refreshes with old data again and withdrawn NFTs come back

**Comment by iotaflea** [comment]
opening another issue now.  deposit NFT sent to deposit address and stayed there. nothing happened...

**Comment by adamunchained** [comment]
> Ok things seem to be moving forward. Owners seem to now be updated. but the collection page now doesnt display listing prices or anything. ![image](https://private-user-images.githubusercontent.com/112674501/329038376-b63b6b1e-a74c-452c-a918-df61becc86f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTEyODIsIm5iZiI6MTcxNTIxMDk4MiwicGF0aCI6Ii8xMTI2NzQ1MDEvMzI5MDM4Mzc2LWI2M2I2YjFlLWE3NGMtNDUyYy1hOTE4LWRmNjFiZWNjODZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQyMzI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWM4MzU0YmIxZjBjYjlkMmIxYzQ4N2FjZjljOGNiODE4ZGMyMzJmNzE4N2I1MzJkZDg0YmM0Zjk5N2I5MGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s3bj15ok1RA1EB_3WfPzVnGgH8ewbSX5qOa-aDyX6oY)

What do you mean by listing price? If I select NFT on Sale it shows them and their price.

**Comment by adamunchained** [comment]
@flyingrabbit-lab - I think I understand the issue. This is due Algolia as suspected. Soonaverse really need to stop using it. It causing all these issues. It should use the API directly to produce lists.

Syncing into Algolia is not properly synching "date" across. See availableFrom is coming back as empty Timestamp in the Algolia's result: 
<img width="1726" alt="Screenshot 2024-05-08 at 4 38 39 PM" src="https://github.com/soonaverse/app/assets/130610/121c85fe-952d-470e-88ff-019dfe69c9bc">

**Comment by flyingrabbit-lab** [comment]
Algolia should be up to date now. Could you check please?

**Comment by adamunchained** [comment]
It was a Soonaverse issue, I've just pushed fixed and released into prod. There was an inconsistency how Soonaverse deals with date field on availableFrom coming from Algolia.
