### ISSUE TITLE
Deposited NFT sent to deposit address and was never deposited, stayed on deposit address

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#153]
NFT sent to deposit address:  smr1qzghewf3unfnyqj3erscasvpktwtl9c4n9slvje0dcpjjnukfjn0q4j47ue
Never actually deposited onto soonaverse user account: 0x186537adEd28Af8EC291a52E84AcdD383384a69c

https://explorer.shimmer.network/shimmer/transaction/0xc1a3d913f7d5753988456834f3e4a8c9969ae563c3c8b4b5b809f307a3fb8cb1

**Comment by flyingrabbit-lab** [comment]
Have you used Soonaverse to deposit this NFT or OTR? 
I can't find this address within our custody.

**Comment by iotaflea** [comment]
Yes I just did it through soonaverse.  This was the soonaverse generated deposit address.  Unfortunately do not have a screenshot of it.  Probably related to the other issue just submitted where user purchased NFT and sent SMR and soonaverse generated address simply kept SMR and user never received NFT.

**Comment by flyingrabbit-lab** [comment]
We had a temporal error, NFT should be credited back. Please check and retry.
