### ISSUE TITLE
NFT purchase failed.  NFT never sent but payment kept.

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#154]
A purchase for an NFT but it was never sent and it kept the SMR.

https://explorer.shimmer.network/shimmer/transaction/0x0593f7c62d3ce521b28bad50c277858686f94c9393bff12c6a830547377ab654

Was for NFT:
https://soonaverse.com/nft/0xb9882fa5ea9197efcfe39f148df3bb16536c727e

**Comment by flyingrabbit-lab** [comment]
We had a temporal error, funds were credited back, please check and retry
