### ISSUE TITLE
Cancelled token trading transaction stuck in processing

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#156]
Soonaverse user:  0x9cf7266a665d4dc785bc37f1f5bcc9f2805ddd2f

User has cancelled a token purchase and the funds have not been returned and stuck in processing.  States that the transaction ID is:  0x9dc4495645e7a1e9708f902244b656c77a49d6a9b0b0b003bade5e2f77dcd99bf9

![image](https://github.com/soonaverse/app/assets/112674501/b25c463f-f144-4837-9ce0-b381f939c889)

**Comment by iotaflea** [comment]
@flyingrabbit-lab are you able to help here?

**Comment by flyingrabbit-lab** [comment]
Yes, fixed
