### ISSUE TITLE
User unable to update IOTA verified address

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#157]
discord ticket: 578

User reports repeat issue in inability to change verified IOTA address, however changing SMR address has no issues.  I think others have reported in past. 

User EVM account: 0x2390731d0eDA70a349DA1fd70941475b87329eF2

These were the transactions which did work for updating the IOTA verified address: https://explorer.iota.org/mainnet/transaction/0x39bb49b55a3c5aa23fea78932ba5ed7d76668969a936f477c3c3bf1cd07f99fb
https://explorer.iota.org/mainnet/transaction/0x862aba8f0fc892ff8f62f291b7b9887c19e3a764ac612e651c7249d69a57f5af

**Comment by flyingrabbit-lab** [comment]
Could you ask the user to retry, it should work now?
