### ISSUE TITLE
User SOON amounts and staked status appear incorrectly.

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#159]
Many users report incorrect or missing information on profile page despite active SOON staking status:

Example 1: https://soonaverse.com/member/0x111c9eadca33b552499466f231b6e4ed7848e50a
User has active stake but profile page shows zero.

![image](https://github.com/soonaverse/app/assets/112674501/80d3c4a9-42cd-43d7-9128-a553ce6d947c)
![image](https://github.com/soonaverse/app/assets/112674501/3f63104a-37bd-48c4-bd04-0d133286fc4e)

Example 2:  SOON staking status shows a negative amount despite active stake
![image](https://github.com/soonaverse/app/assets/112674501/32443912-383a-4112-a9bb-15bca4851aff)

**Comment by MF080961** [comment]
I am old mifer, they told me to got o github and I se my case my file is alreay there, so i ma not a tech guy, but please i need help
I stekd more than 15 k no idea where they are and i think also my builder rewards amountis not correct . Please what to do?
