### ISSUE TITLE
Cancelling order did not return remaining funds

### ISSUE THREAD

**Issue by gjeee** [soonaverse/app#160]
i cancelled a sell order on iota/smr exchange. order got cancelled but remaining iotas have not been returned.
remaining amount is 10,000-31-184.65-13-3-10=9758.35 IOTA and still sits on address https://explorer.iota.org/mainnet/addr/iota1qrh66wxdq0fek04u55tu2ryakar6wmtea90ayupfkkp8h6emud8uq5cw98k

my profile is https://soonaverse.com/member/0x5a22618a380a56c20a0c26664c3955d594f426e8/activity

![image](https://github.com/soonaverse/app/assets/13155183/881cedbd-3fe1-481c-b196-deea4bdd8e4a)
![image](https://github.com/soonaverse/app/assets/13155183/e78d18d3-d5fe-45f6-bbc0-3b684198814b)

**Comment by iotaflea** [comment]
@adamunchained @flyingrabbit-lab  Is this able to be resolved by releasing funds if they are on soonaverse controlled addresses?

**Comment by adamunchained** [comment]
should be fixed as part of the https://github.com/soonaverse/app/issues/182
