### ISSUE TITLE
Collection mint to Iota is freezing

### ISSUE THREAD

**Issue by Rawkala** [soonaverse/app#162]
**Collection mint to Iota is freezing**
While minting the Collection to Iota the process is freezing at a certain point since a few days.

**To Reproduce**
- Collection: https://soonaverse.com/collection/0xd80358d615dadb1895e123ca25c7e76cd769851c
- Freezing at "43 NFTs left"

- https://soonaverse.com/collection/0x7c1a450717c94761ec375399dfe08cd982d80725
- Freezing at "2200 NFTs left"

**Screenshots**
![image](https://github.com/soonaverse/app/assets/172172736/6701de0e-75d1-4d87-9bb3-e19d8f8e3895)

**Comment by IOTAPUNKS** [comment]
Yesterday I was able to successfully migrate three collections. Unfortunately, the migration process froze for these three other collections. Please fix this error, thank you!

https://soonaverse.com/collection/0x2464e5b0728f3d35f97ef16bd60c3b8f831dbf56
https://soonaverse.com/collection/0xc95de0524b2112a36701b9d3465e61772ae6ce8e
https://soonaverse.com/collection/0xe74eefe6d367bee07c88b167524036c03e74bed5

![Screenshot 2024-06-09 102130](https://github.com/soonaverse/app/assets/36330992/59f7b430-beea-4640-8596-b273b516c9e9)

**Comment by whatmicha** [comment]
Adding Moonaco Captains to this 

https://soonaverse.com/collection/0xb3543424af9cc39052d84f527f382bf24e26da20

**Comment by centercirclesolutions** [comment]
@adamunchained This seems similar to the other minting issues has the resolution solved this as well?

**Comment by IOTAPUNKS** [comment]
I don't know if the problems with the other collections have been solved, but with my three collections the problem still exists in any case. 

@centercirclesolutions Thanks for the support!

**Comment by whatmicha** [comment]
Adding LendeXe NFTs 

https://soonaverse.com/collection/0x7ce279815e2910a6341d6ff04d9dd7990f8252be
https://soonaverse.com/collection/0x18b1de447289c85754b9b0de1e5acdbac49597be
https://soonaverse.com/collection/0x021b5b27ead6ec003ba8f1b605f853a5baf9a803

**Comment by adamunchained** [comment]
> @adamunchained This seems similar to the other minting issues has the resolution solved this as well?

There seems to be an issue with minting on some collections. Right now, we have got different priorities but when we find availability we will try to assist.

**Comment by whatmicha** [comment]
adding another One
Munkii Orbii 
https://soonaverse.com/collection/0xb7d1441a1f6136acb25f874086740c588d597878

**Comment by IOTAPUNKS** [comment]
Adding DUNKIN DUDES - #The Poker Punk Giveaway Collection

https://soonaverse.com/collection/0xa424d4878f2999d177da46b2c6a82166e53b59bf

**Comment by whatmicha** [comment]
Adding Iotaholics

https://soonaverse.com/collection/0xceb05094fb7f3f480ed299e35bb9e1a171484252

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
