### ISSUE TITLE
Two Stuck Transactions (since 05/26/2024)

### ISSUE THREAD

**Issue by Eyerkaufer** [soonaverse/app#163]
Hi,

i have two transaction which seem to be still in the processing state since the 05/26/2024:
![image](https://github.com/soonaverse/app/assets/32290855/c5972f91-51ce-462f-89f9-083afac839aa)

uid: 0x1dcae8bd2209fc8c7603bd6ca7d4e42022c262bd
uid: 0xd8fd096d93d8efe3a7401f619ddc65eeb5591f7f

This is related to the discord bugissue-587.

Can you please support in fixing this problem?

**Comment by Eyerkaufer** [comment]
Here are also the two Soonaverse links to the NFTs (however, they no longer work).
https://soonaverse.com/nft/0x40e0cfe6e5459d8029fcb37ad0a47e1827289bdd
https://soonaverse.com/nft/0x26ea504017917caf85b39e49a5ce9a6c61d8dbe5

**Comment by Demistumod67** [comment]
@Eyerkaufer It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
