### ISSUE TITLE
I can't claim my tokens

### ISSUE THREAD

**Issue by MrRo-de** [soonaverse/app#164]
Hi, 
I've tried to claim my tokens on soonaverse. Everything worked to the point where I sent the "fee". I've send it on my side, but then nothing happens on soonaverse. There's just the message "waiting for payment".

https://explorer.shimmer.network/shimmer/transaction/0x16c16d5214fb1ce6f2cebe9f2e9bb0135634fb901c0170d64cba853762cc9b2b

**Comment by SoonIota** [comment]
Hi, I have the same issue. Sent fees to soonaverse claiming address from Shimmer Firefly two times and successful, then nothing happened. I can still see the soon token to be claimed under Token page in my soonaverse profile. Pls see transaction details below. Many thanks.

https://explorer.shimmer.network/shimmer/transaction/0xf37fd6ac9ba770e7112275d3362162cebaee97d6dabd62570fb02fa472355311

https://explorer.shimmer.network/shimmer/transaction/0x08541df72a5d6b83869066fb1a2f8ab8bbcdce092a759efc15327feda3b6e2ec

# I opened a ticket already for this issue (Bugissue-595)

**Comment by ThomasethDev** [comment]
@MrRo-de @SoonIota It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Demistumod67** [comment]
@MrRo-de @SoonIota It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
