### ISSUE TITLE
api request to retrieve orderbook returns 404

### ISSUE THREAD

**Issue by gjeee** [soonaverse/app#165]
Since migration below api request does not seem to work anymore. It returns 404 :-(

GET /api/getMany?fieldValue[]=0xf0ae0ebc9c300657168a2fd20653799fbbfc3b48&collection=token_market&fieldName[]=token&fieldName[]=status&fieldValue[]=active HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIweDU1MWZkMmM3YzdiZjM1NmJhYzE5NDU4N2RhYjJmY2Q0NjQyMDA1NGIiLCJwcm9qZWN0IjoiMHg0NjIyM2VkZDQxNTc2MzVkZmM2Mzk5MTU1NjA5ZjMwMWRlY2JmZDg4IiwiaWF0IjoxNzAwMDAyODkwfQ.IYZvBRuCiN0uYORKnVJ0SzT_1H_2o5xyDBG20VmnTQ0
Host: api.buildcore.io
Accept: application/json

**Comment by emmap3-do** [comment]
Try this:

`https://api.buildcore.io/search/getMany?fieldValue[]=0xf0ae0ebc9c300657168a2fd20653799fbbfc3b48&dataset=token_market&fieldName[]=token&fieldName[]=status&fieldValue[]=active`

**Comment by gjeee** [comment]
ok that seems to work....tx

> Try this:
> 
> `https://api.buildcore.io/search/getMany?fieldValue[]=0xf0ae0ebc9c300657168a2fd20653799fbbfc3b48&dataset=token_market&fieldName[]=token&fieldName[]=status&fieldValue[]=active`

**Comment by gjeee** [comment]
closing ticket
