### ISSUE TITLE
Withdraw NFT

### ISSUE THREAD

**Issue by borninchb** [soonaverse/app#166]
**Describe the bug**
I have withdrawn several NFT on june the 10th and they process is still not finshed

1. Go to "NFT" 
2. Click on 'withdraw NFT'

**Expected behavior**
NFT should have arrived in my wallet already.

**Screenshots**
![image](https://github.com/soonaverse/app/assets/95142017/81d34b8b-abc7-430f-a479-b47a9bc329ef)

**Desktop (please complete the following information):**
 - Linux Mint: [e.g. iOS]
 - Brave [e.g. chrome, safari]
 - [Version 1.66.118 Chromium: 125.0.6422.147 (Offizieller Build)](https://brave.com/latest/)  [e.g. 22]

**Additional context**

**Comment by IOTAPUNKS** [comment]
The following three collections have recently been migrated to the Shimmer network.

https://soonaverse.com/collection/0xc82e411becaabbad32615630acdef46f433b699e
https://soonaverse.com/collection/0x59b7a99635522cdf978a5a384895c37930774abc
https://soonaverse.com/collection/0xcd8f364bf020613a1c8a1181ac94ddab425bc6f2

When transferring these NFTs to the private wallet, an error occurred in many cases and the
error and the NFTs were not transferred, but are also no longer available on 
Soonaverse are no longer available. Please check all incorrect transactions
transactions in this account.

https://soonaverse.com/member/0x8a018b13922a89ec4ad136bbacd8a084e1d149cb/transactions

Here is the corresponding SMR address.

https://explorer.shimmer.network/shimmer/addr/smr1qq0gv6r3kesuqrfduap6y4pwxp77r299eughqm9axssaz7aec6yc73t7nrn

Thank you for your support!

![fail](https://github.com/soonaverse/app/assets/36330992/fac12ab7-3152-4317-8705-99e7a7dd9164)

**Comment by IOTAPUNKS** [comment]
File with withdrawn NFTs.
[soonaverse_0x8a018b13922a89ec4ad136bbacd8a084e1d149cb_transactions.csv](https://github.com/user-attachments/files/15832025/soonaverse_0x8a018b13922a89ec4ad136bbacd8a084e1d149cb_transactions.csv)

**Comment by IOTAPUNKS** [comment]
@adamunchained  more and more people are having problems sending their NFTs from Soonaverse to their own wallet. I have 86 NFTs that have not arrived. 

Please be so kind and take care of the problem, thank you!

If you need more information to solve the problem, please feel free to contact me at any time.

**Comment by borninchb** [comment]
Meanwhile I have received all my withdrawn nfts. Hope the cases you @IOTAPUNKS reported can also be closed in a shorter period.
