### ISSUE TITLE
NFT Withdrawal Stuck in Processing

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#167]
NFT withdrawal transaction stuck processing.

Soonaverse user: 0x7bc605870af28e5bd544614bad2402468cd37e21
Transaction uid: 0xf8a008406138d93bf4d0301f412ae15145315295
NFT: https://soonaverse.com/nft/0xa37741c8912f292cfc5ac7d8f45dfb7df1f022ae

![image](https://github.com/soonaverse/app/assets/112674501/eef219a4-0684-4c0f-bef5-097ad160a79e)

**Comment by ThomasethDev** [comment]
@iotaflea It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
