### ISSUE TITLE
NFT withdrawal stuck in processing

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#168]
User: 0xbeb127e9008139078ed905e20fcbc4feaebb4116
uid: 0xd3240ca94e90dedf0b89cb4f67033e8d3fb1c749
NFT: https://soonaverse.com/nft/0x4ba5a24f59dd68024fd7b8f85ab13bbc92759af0

![image](https://github.com/soonaverse/app/assets/112674501/71039d88-3eed-40d4-864a-efb543095ff1)

**Comment by KryptoniteAli** [comment]
Thanks, waiting for solution before withdrawing again..
