### ISSUE TITLE
Multiple Sell Orders Cancelled and Transactions Stuck Processing

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#169]
User: 0x582ef1d2aa6ba24e9ee9ebfecbbf8b309335ed4c
uid: 0xaa75baa652b8928645c36bf3aa832e42173b24d5
uid: 0xfabc3d797f04f12dfe370272b02ad008491ee5be
uid: 0xc943a088684fe5c04179e27bf13b932fd8e071cd
uid: 0xf4e6f4217ac08b3fadc83a680e20cf5e744d6a89

![image](https://github.com/soonaverse/app/assets/112674501/d5fdebf0-20e3-4267-83db-45a81632f38f)

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182

**Comment by Myhouses07** [comment]
add up three(3) more transaction stuck
User: 0x582ef1d2aa6ba24e9ee9ebfecbbf8b309335ed4c

![IMG_2767](https://github.com/soonaverse/app/assets/135076242/d8989daa-3cb4-44f8-8e39-1bf9b08e936f)

**Comment by HanueDev** [comment]
@tangler07 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Soonaverse Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
