### ISSUE TITLE
NFT withdrawal gets stuck in the processing of 88 NFTs

### ISSUE THREAD

**Issue by IOTAPUNKS** [soonaverse/app#170]
Sorry for the repetition, but my first request was closed by the issue creator.

The following three collections have recently been migrated to the Shimmer network.

https://soonaverse.com/collection/0xc82e411becaabbad32615630acdef46f433b699e
https://soonaverse.com/collection/0x59b7a99635522cdf978a5a384895c37930774abc
https://soonaverse.com/collection/0xcd8f364bf020613a1c8a1181ac94ddab425bc6f2

When transferring these NFTs to the private wallet, in many cases an error occurred and 
the NFTs were not transferred. These are also no longer available on Soonaverse. Please 
check all incorrect transactions on this account.

https://soonaverse.com/member/0x8a018b13922a89ec4ad136bbacd8a084e1d149cb/transactions

Here is the corresponding SMR address.

https://explorer.shimmer.network/shimmer/addr/smr1qq0gv6r3kesuqrfduap6y4pwxp77r299eughqm9axssaz7aec6yc73t7nrn

Thank you for your support!

![fail](https://github.com/soonaverse/app/assets/36330992/fac12ab7-3152-4317-8705-99e7a7dd9164)

File with withdrawn NFTs.
[soonaverse_0x8a018b13922a89ec4ad136bbacd8a084e1d149cb_transactions.csv](https://github.com/user-attachments/files/15832025/soonaverse_0x8a018b13922a89ec4ad136bbacd8a084e1d149cb_transactions.csv)

There are currently a total of 88 transactions that have not arrived!

@adamunchained  more and more people are having problems sending their NFTs from Soonaverse to their own wallet. I have 88 NFTs that have not arrived. 

Please be so kind and take care of the problem, thank you!

If you need more information to solve the problem, please feel free to contact me at any time.

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
