### ISSUE TITLE
NFT withdrawal stuck in processing

### ISSUE THREAD

**Issue by whatmicha** [soonaverse/app#171]
**Describe the bug**
Stuck TX on Withdrawal (conflicting)

**UID** 0xbf427cf6e9688fdbc8ee0e44e80e4cb827c693ba

Those are tx UID if something more is needed plz tell me 
Both Munkii 2D tx UID
0x4e61993719c7ca8319fc618a7677f9695ed9ce54
0x9e50a15fd15c0d444c0c02a18c0d3161509eebe3
Munkii Believer tx UID
0x9b691291435168f8825420caacc0e5257891d063
https://explorer.iota.org/mainnet/search/0xbc50664accfba5df251ddc83e0f6068509dc29e91ccc3e9cf5e67cc21d69c086 (munkii 2D) 
https://explorer.iota.org/mainnet/search/0xdfacb875861607f697589df673adf9bfd16fa6ed9f1bc0d65cb2325e83e44a24 (another munkii 2D)

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
