### ISSUE TITLE
My ShiWeas withdrawal got stuck with invalid Signature

### ISSUE THREAD

**Issue by Phyloiota** [soonaverse/app#173]
**Describe the bug**
Withdrew ShiWeas

TX is conflicting because you used an invalid Signature

https://explorer.iota.org/mainnet/block/0x95e325e637ce7d90cb42ef46b52e66e73500d0726417eb43e110f59ad8ec9338?tab=Payload

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
