### ISSUE TITLE
NFT withdrawn on june 9th ...

### ISSUE THREAD

**Issue by renewid** [soonaverse/app#174]
Same problem like many others here: since then the "Transactions"-Page shows this NFT-Withdraw as "Processing". I can provide the link if needed.

**Comment by Demistumod67** [comment]
@renewid It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
