### ISSUE TITLE
NFT withdrawal stuck in processing

### ISSUE THREAD

**Issue by whatmicha** [soonaverse/app#175]
Users IOTA L1 Address: iota1qqrt3msgkgqtnwutuxq78ywnnxnaww2x769nz9yzcwgfv7w7gzppg0yh603

![image](https://github.com/soonaverse/app/assets/110422993/79809c57-3475-4f69-b7fc-05771ee46fde)
![image](https://github.com/soonaverse/app/assets/110422993/7f437706-eb57-43b1-a307-fdeab9da0ff4)

**Comment by Demistumod67** [comment]
@whatmicha It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by emmap3-do** [comment]
So now we have scammers here too. @Demistumod67 scammer get out of here!

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
