### ISSUE TITLE
Munkii 444 OG Collection - Minting issue

### ISSUE THREAD

**Issue by wiredutch** [soonaverse/app#176]
Same as every other issue:

The Munkii 444 OG Collection is in MINT FREEZE.

https://soonaverse.com/collection/0x35edbce12110b233441a11847ab72cd2eac7ed49

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
