### ISSUE TITLE
Withdrawing two NFTs with the same issue ( Conflict )

### ISSUE THREAD

**Issue by wiredutch** [soonaverse/app#177]
After Minting one of the Munkii collections ( Punkii ) I tried on two separate occasions to withdraw two NFTs to test.

Both NFTs should have landed in my own IOTA wallet, but both have conflicts. I have lots of other NFTs to withdraw but after the 100% failure rate to the IOTA network, I guess it is not safe to do so.

Here are the two transactions:

https://explorer.iota.org/mainnet/block/0x5d4f9c2872954b6b6df660f48f46270e5b3e16fc3010c55835f5853ec4465203?tab=Payload

https://explorer.iota.org/mainnet/block/0x191710a05732dcef762fd2007cddd1e806b02f62d12699c412c30aa7f222daa6

**Comment by ThomasethDev** [comment]
@wiredutch It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182

**Comment by tangler07** [comment]
here I add same issue of withdraw NFTs like four(4) conflicting on mainnet as below;
1. https://explorer.iota.org/mainnet/block/0xeb449f6dca5145e35a788fb3feff19b2eb143924fcb64d2a5e46c2874110034a
2. https://explorer.shimmer.network/shimmer/block/0xe8babbe0725f56ccba42c800ef6ac4ba35d79f456d6d5fe7735490d37a977316
3. https://explorer.shimmer.network/shimmer/block/0x43516ab7b00eedf6f0267444a38ee1db22bc1652a176aac75e4be79cd5929a99
4. https://explorer.shimmer.network/shimmer/block/0x9d2b7802425fd32021b028efb57fcd28f63844ed01e5f0f1b769f78931add73c
