### ISSUE TITLE
 Lost NFT's IOTAPUNKS collection

### ISSUE THREAD

**Issue by Javierh1971** [soonaverse/app#178]
I have withdrawn my NFT #The Punk Comic Collection - 111 from Soonaverse and it has not arrived in my Firefly wallet.
And the same with #The 3D Punk Token Collection - 29

**Comment by Javierh1971** [comment]
uid: 0xcadb32360a702fea2774a34563c046c843670cc1, tries: 6
uid: 0x00c5c483e9e3d09c7407d4722c9af4e314e0bafb, tries: 6

**Comment by Javierh1971** [comment]
Another that remains processing...
uid: 0xe14531a7127097f12ae42bb1b9a2241ccbcbd4a1, tries: 6

**Comment by ThomasethDev** [comment]
@Javierh1971 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Demistumod67** [comment]
@Javierh1971 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
