### ISSUE TITLE
NFT withdrawal stuck in processing

### ISSUE THREAD

**Issue by emmap3-do** [soonaverse/app#179]
Original NFT Url:
https://soonaverse.com/nft/0x8faf874c3307c139a793f7486db138f48c4d2c31a568f2eeb1dfa51933662d98

uid: 0x0c3e3206a38ce16b8a8bedb0c50a287b7eea347d

![image](https://github.com/soonaverse/app/assets/124573743/7a415fe0-e45c-4958-9e98-f89a9934cd6e)

**Comment by adamunchained** [comment]
related to https://github.com/soonaverse/app/issues/182
