### ISSUE TITLE
Stuck NFT withdrawals THE 99 SHI-WEAS / Munkii

### ISSUE THREAD

**Issue by Iven83** [soonaverse/app#183]
THANK YOU!!! 

A. THE 99 SHI-WEAS

tranUid: 0x2b3e40300275343a84422616c8301b178ff9afb9
nftUid: 0x5a03d1e7d5cfb019a17b8c0af4d04b771472ff01
https://soonaverse.com/nft/0x5a03d1e7d5cfb019a17b8c0af4d04b771472ff01

B. Munkii 100 2D OG NFT Collection

tranUid: 0xbd14c9c918db8d4494cbf213d15939515c045efa
nftUid: 0x11b19c49fa46dd6bec1d9f30ee60c42e0fdd8179
https://soonaverse.com/nft/0x11b19c49fa46dd6bec1d9f30ee60c42e0fdd8179

**Comment by Iven83** [comment]
@adamunchained any News about stuck/processing NFTs?

**Comment by adamunchained** [comment]
should be fixed as part of the https://github.com/soonaverse/app/issues/182
