### ISSUE TITLE
NFT withdrawal still processing...

### ISSUE THREAD

**Issue by Iven83** [soonaverse/app#184]
many thanks in advance!

**Describe the bug**
NFT withdrawal still processing...

A. SHI - UNIVERSE | LIMITED ARTWORKS - ITEM 02 - THE FIELDS OF GLIMM
uid: 0x2273dae79495634f05bb05d01d10f7fbae3456
https://soonaverse.com/nft/0x688772cc2d3251ad386dd4c943c1986abc606ace

B. IOTAPUNKS - #The Punk Comic Collection
uid: 0x972969299da156f2ef3ee8bf9b814c433550b0
https://soonaverse.com/nft/0xe2bc529d5d9b4b18b7231993ea170ee9cb80fa84

C. IOTAPUNKS - #The Punk Comic Collection
uid: 0x750081ba33587ad1a449d6128e6c892afd9144fd
https://soonaverse.com/nft/0x585a5cb83153b0bf5605cd5c7f099cea445a7f24

D. IOTAPUNKS - #The Punk Comic Collection
uid: 0x9e693cf480246ed938fb7df7384151daf3ef7623
https://soonaverse.com/nft/0x0395389f26220ee8b469bf46bacfeff43825c182

E. IOTAPUNKS - #The Punk Comic Collection
uid: 0xc0e2c8c84f1e1e289401e1e94c63f721950601d5
https://soonaverse.com/nft/0x3cda9fd962bd16bd9df0e45475090d9d9fab7c20

F. IOTAPUNKS - #The Punk Comic Collection
uid: 0x2cabb441d5eedb89afdd99170eb4a2af1f7c8818
https://soonaverse.com/nft/0x576e1cf994292a9864dcda514ed5b9c54f28dcf4

**Comment by Demistumod67** [comment]
@Iven83 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
should be fixed as part of the https://github.com/soonaverse/app/issues/182
