### ISSUE TITLE
Canceled order soon/smr don't arrieved back to wallet 

### ISSUE THREAD

**Issue by wojownik1985** [soonaverse/app#185]
Hi,
my canceled order soon/smr don't arrieved back to my wallet.
In my transaction history the order is still in 'processing'
My soonaverse profile https://soonaverse.com/member/0xd562a17ce3079f2f8f77374d14ef5d01dca1f2fb/transactions

The smr were sent to this address: smr1qz8vmj3upmrjmh7r23n2fjsk37j5emvc3np3enq5rftj933yhfgyzgy3649
Transaction: https://explorer.shimmer.network/shimmer/transaction/0x1390456d60fdbc80e6bdf2c170558685efab0ffb89381975c12857932b18b577
Hope it will be solved fast, thanks

**Comment by Demistumod67** [comment]
@wojownik1985 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
should be fixed as part of the https://github.com/soonaverse/app/issues/182

**Comment by wojownik1985** [comment]
Thanks, got the missing smr
