### ISSUE TITLE
Daobee Collections not minting

### ISSUE THREAD

**Issue by xPathin** [soonaverse/app#186]
We tried to mint our daobee collections to IOTA L1, even  sent funds but the transaction was never credited and was also not sent back.
Please mint our collections for us to IOTA L1.

https://soonaverse.com/collection/0x9b996f998833ae98d155a83cc67c16514a9e5b0c
https://soonaverse.com/collection/0x519ccc6046083ec07132951ccab0e571777449de
https://soonaverse.com/collection/0x454fe8b9d5320ef576d482143a41f77e5e505113

**Comment by xPathin** [comment]
#182 182

**Comment by borninchb** [comment]
https://discord.com/channels/914203885231542332/962105032180899960/1249636264798326845

**Comment by adamunchained** [comment]
should be fixed as part of the https://github.com/soonaverse/app/issues/182
