### ISSUE TITLE
Buying NFTs leads to stuck funds

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/app#187]
I just tried to buy 2 pharao´s. Put them in my cart at soonaverse, paid 13000 smr, but nothing happened... smr is gone. Soon didn´t pick up transaction, and it expired.. I used the Firefly deeplink and checked if metadata was correct. 
Tx: https://explorer.shimmer.network/shimmer/transaction/0x63b5873c2acde0940c61cb0e0c2c4c4a93496b62a3674f6d550e8fc7d8333734 (edited)

Please return my funds ASAP. If the platform isn't working it should be clear from the website and the functinality to buy NFTs should be disabled.

**Comment by HanueDev** [comment]
@ivanbeerlama It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Soonaverse Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ivanbeerlama** [comment]
Lol, first I got scammed by Soonaverse and now you're trying to scam me @HanueDev, go eat some shit.

**Comment by HanueDev** [comment]
@ivanbeerlama It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ivanbeerlama** [comment]
@adamunchained , thanks for returning my funds!
