### ISSUE TITLE
Withdraw NFT conflict "The unlock block signature is invalid"

### ISSUE THREAD

**Issue by borninchb** [soonaverse/app#188]
![image](https://github.com/soonaverse/app/assets/95142017/1718f57f-5c76-4538-aaa7-759e94925c82)
![image](https://github.com/soonaverse/app/assets/95142017/6f78d2be-3f64-4e92-b5c2-3923f9f7c425)

I have withdrawn some nfts and they doesnt arrive in my wallet. 
All these transactions are in the attached file.
[Munkii und Orbii.xlsx](https://github.com/user-attachments/files/16138538/Munkii.und.Orbii.xlsx)

**Comment by HanueDev** [comment]
@borninchb It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by adamunchained** [comment]
should be fixed as part of the https://github.com/soonaverse/app/issues/182
