### ISSUE TITLE
Stuck NFT withdrawals still processing

### ISSUE THREAD

**Issue by Wagminaut** [soonaverse/app#189]
I still have many NFT withdrawals stuck in Soonaverse. Could you please check these and help to get them through?

My address is 0x4533863098a8dc2ed469a0f791d0b07261bb33d9

Transactions that are still processing after withdrawal:

Asset,2024-07-06T07:59:08.916Z,168100,,,,0xce4c84f1f450061a535c801cbe49eaa292843d1b,0xdb47fa3d6cdc14910933d0074fba36a396771bfa,,

Asset,2024-07-06T07:59:03.743Z,183200,,,,0x2faec1dfcca5a92172f27a6321dffad20a3e56d7,0x287eb6a8c83a352debe57bf0f3a96f30ff734825,,

Asset,2024-07-06T07:58:58.797Z,136500,,,,0x52140ac2090b944eef6499536c17397a2029ddfb,0x26f5cb9980b9e1b7a84aaf7c0b8188bb9774bd99,,

Asset,2024-07-06T07:58:37.301Z,103300,,,,0xe44c93930c0638cc3e25e575e9c078b9cb99f15a,0xbcbfad2b95862666831c46a897ced7db46e156e5,,

Asset,2024-07-06T07:57:37.793Z,170200,,,,0x721e9f3f0ab615cf4c62f48d1bbc28b673a0a97b,0xcbe28532602d67eec7c937c0037509d426f38223,,

Asset,2024-07-06T07:57:06.472Z,321000,,,,0x119b13ee78d787662c79acf2361c6ba5e4b04cc3,0xa60d33c3787e1e17a8df4ba16f4429317fa53327,,

Asset,2024-07-06T07:57:01.619Z,321100,,,,0x065de1d52f4580423a79d3655b330abe44b470dc,0xa60d33c3787e1e17a8df4ba16f4429317fa53327,,

Asset,2024-07-06T07:56:55.627Z,182300,,,,0x19515740d6c2262ee352e7a0e32ab6da71186094,0x287eb6a8c83a352debe57bf0f3a96f30ff734825,,

Asset,2024-07-06T07:56:49.312Z,182400,,,,0x24b094434266ff7abfc4e93366d4c24cb3fa2cda,0x287eb6a8c83a352debe57bf0f3a96f30ff734825,,

Asset,2024-07-06T07:56:22.273Z,182300,,,,0x4bea5b5271b725722a942839e413ce58a9917b87,0x287eb6a8c83a352debe57bf0f3a96f30ff734825,,

Asset,2024-07-06T07:56:14.673Z,183200,,,,0xa5fb8cb2f95291829d2086bddee5a0ebd78e9e7b,0x287eb6a8c83a352debe57bf0f3a96f30ff734825,,

Asset,2024-07-06T07:55:52.865Z,182200,,,,0xc871d90fdfa47d0b24b53855c5b3025099ba1830,0x287eb6a8c83a352debe57bf0f3a96f30ff734825,,

Asset,2024-07-06T07:55:47.645Z,135800,,,,0xa1914a8bad9187d5e65a9d3aea592a791962417e,0x26f5cb9980b9e1b7a84aaf7c0b8188bb9774bd99,,

Asset,2024-07-06T07:55:42.184Z,136100,,,,0x6eb3fad993205d134ed1ea35675308814fb4de4e,0x26f5cb9980b9e1b7a84aaf7c0b8188bb9774bd99,,

Asset,2024-07-06T07:55:36.229Z,136200,,,,0x57debba5abbb8ab4659bfd36c59966490f06bd60,0x26f5cb9980b9e1b7a84aaf7c0b8188bb9774bd99,,

Asset,2024-07-06T07:55:27.591Z,136300,,,,0x0073691ec58a695a8271425c5e7bfdc9f0b74c1b,0x26f5cb9980b9e1b7a84aaf7c0b8188bb9774bd99,,

Asset,2024-07-06T07:55:11.828Z,99200,,,,0x8f22e9a989f6881d2f782c68aafc491ee379f265,0x9d05a5d34ae4062d732a535851db2d344409356b,,

Asset,2024-07-06T07:55:03.256Z,98500,,,,0x4baf344973fbd97e2a09ea28847744818d9526ce,0x439c87f97ece722312162a0b60bb27deb6908ab9,,

Asset,2024-07-06T07:54:57.025Z,173200,,,,0x06c25491db7b3f5a46d5aaddc933a8f3276c525e,0x1fae1a8558b57591c3de2aacc0d3df1802eff2ab,,

Asset,2024-07-06T07:54:51.593Z,170500,,,,0x059759fadbc4935e29690022387fdc6bf92f3ec4,0xcbe28532602d67eec7c937c0037509d426f38223,,

Asset,2024-07-06T07:54:46.107Z,169000,,,,0x07ebc81be0804db60821d8e4feea20006008e3ef,0xdb47fa3d6cdc14910933d0074fba36a396771bfa,,

Asset,2024-07-06T07:54:40.013Z,174000,,,,0x12d3752e722929fd800ce6da545be7f9b88a7747,0x1fae1a8558b57591c3de2aacc0d3df1802eff2ab,,

Asset,2024-07-06T07:53:34.047Z,170500,,,,0x20cc657a41bf845828c31ce981dbfdeb0a28c9a9,0xcbe28532602d67eec7c937c0037509d426f38223,,

Asset,2024-07-06T07:53:27.711Z,168100,,,,0x1b4adac6b00334e209d656dd5efa106c116d9d93,0xdb47fa3d6cdc14910933d0074fba36a396771bfa,,

Asset,2024-07-06T07:53:20.773Z,173800,,,,0xdd7acc3c74cca3cdf69d2dc144cd339ac34a4a49,0x1fae1a8558b57591c3de2aacc0d3df1802eff2ab,,

Asset,2024-07-06T07:53:12.106Z,173500,,,,0x270a064f5ab44feb8a8282a2e3935ba5980374ff,0x1fae1a8558b57591c3de2aacc0d3df1802eff2ab,,

Asset,2024-07-06T07:43:32.641Z,181600,,,,0x821e500b48b53f7ca7f9ca9fabc85abf916d8e77,0x740233f719efd6b7314b7e773c6ce09d6d831a71,,

**Comment by HanueDev** [comment]
@Wagminaut It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://soonaverse-support.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation
