### ISSUE TITLE
Bundle listing for  Soonaverse ULTRAS

### ISSUE THREAD

**Issue by janoschpilz** [soonaverse/app#21]
Since me and a whole of other people wanted to sell their Soonaverse ULTRAS for cheaper as the current floor just for treating the community well.. A "community member" saw that and bought only one of those three nft's...
So let's say the current floor is at 6300 $smr.
I now have a good day and want to sell my ULTRA for 5400 $smr- so basiclly i will put Alien#3534 for 1800 $smr, Soonanaut#3534 for 1800 $smr and Artifact#3534 for 1800 $smr onto sale!
now since i had put the ULTRA 900 $smr cheaper onto the market a person could now buy Alien, Soonanaut or Artifact and just put the same bought nft (1800$smr) for 2700$smr for sale now.
That way he/she is destorying every ULTRA.
If you are enabling bundle Listing make shure we can use Alien, Soonanaut and Artifact in it!
Appreciate your help!

**Comment by emmap3-do** [comment]
I would approach this in a more generic way, so that any bundle can be set for sale (not only ULTRAS). 
See this discussion I opened few months ago:
https://github.com/soonaverse/soonaverse-dao/discussions/1130

**Comment by emmap3-do** [comment]
Re-open issue

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

-this can now be achieved via Swap API: https://developer.build5.com/docs/how-to/swap/create-swap - it just needs front-end integration
