### ISSUE TITLE
Ability to access withdrawn NFTs

### ISSUE THREAD

**Issue by epochzro** [soonaverse/app#24]
Sending an NFTs to shimmer causes the link to be lost from soon.  I would be nice if a placeholder was kept on soon in order to view the complete collection.  A simple flag indicating that the NFT is in another space would be fine.

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is:

- once you have finalized the UI for this, we can release tweak on the B5 API to support it. It's a simple flag.
