### ISSUE TITLE
Bulk Buy & Bulk Transfers

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/app#32]
### Discussed in https://github.com/soonaverse/soonaverse-dao/discussions/1174

<div type='discussions-op-text'>

<sup>Originally posted by **LordSciFi** July 29, 2023</sup>
We want bulk buy & bulk transfers!

One of the most painful situations as a Soonaverse user and NFT enthusiast is that it is not possible to purchase multiple NFTs at once and transfer multiple NFTs at once. This is an absolute standard feature on any other chain.

Elaboration of the pain points:
1. **As a user** - Every NFT has to be minted as a single NFT! Why should i buy 50 NFTs on Soonaverse (as some new to IOTA/SMR/Soonaverse), if i need to do 50 single transactions, this is **so painful** and such a waste of time!
2. **As a user** - If one holds many NFTs he might not want to have all NFTs on one single profile so bulk transfers to move NFTs from one profile to another is an absolute must, without this feature it's the same issue as pain point Nr. 1 
3. **As a Project** -Minting is less attractive as one could say "Hey this is not important we don't care if people waste their time" but actually it also leads to less likelihood that users will mint as many NFTs as they would want since it simply takes too much effort. Thus, projects lose potential new members for their community
4. **As a Project** - Converting users from other ecosystems is incredibly hard since the entire setup is a bit difficult (two or three wallets needed and soonaverse unknown). Additional missing "small details" like a bulk mint feature makes our beloved ecosystem less attractive (it's not about one feature but one smooth overall experience)

Many, many people and projects are waiting for these two feature!
This will also increase the overall NFT sales for the Soonaverse.</div>

**Comment by adamunchained** [comment]
<img width="977" alt="Screenshot 2023-08-15 at 8 27 37 PM" src="https://github.com/soonaverse/app/assets/130610/c07367f1-57ab-46f2-b297-5a677bc8cd96">
<img width="965" alt="Screenshot 2023-08-15 at 8 27 27 PM" src="https://github.com/soonaverse/app/assets/130610/2096d0f2-1e0d-4cd9-bef8-827e2197955a">

**Comment by adamunchained** [comment]
@LordSciFi - I think this is a great proposal and build-5 is very happy to support this. We can enhance purchasing flow API to enable bulk purchase very easily. The mechanics are there. Instead of purchasing just one NFT, you'll be able to buy multiple NFTs at once. 

Let's find a developer that is happy to take on the challenge and develop the UI flow and enhance soonaverse/app. We will support them with API's they need. This effort will of course be generously rewarded with SOON. I would see this as Category 3 and I'm sure SOON Committee and community will be ready to generously reward the effort. See CONTRIBUTING guide: https://github.com/soonaverse/app/blob/master/CONTRIBUTING.md

**Comment by LordSciFi** [comment]
Very happy to hear, great news! 

Alright, starting to ask around :)

**Comment by LordSciFi** [comment]
VERY NICE!👀

**Comment by adamunchained** [comment]
Assigning to Alec as he is already working on this
