### ISSUE TITLE
Run build, tests, lint and prettier on PRs

### ISSUE THREAD

**Issue by labralords** [soonaverse/app#37]
**Is your feature request related to a problem? Please describe.**
When contributing to the project, it would be nice to have some sort of checks that needs to pass on PRs. It will make the process a bit more robust. Build, tests, lint and prettier on every PR.

**Describe the solution you'd like**
All PRs to develop / master will run build, test, lint and prettier on the code.

**Describe alternatives you've considered**
Alternatives is to run this locally, but that requires the dev or reviewer to remember to run lint, prettier, build and tests before merge.

**Comment by adamunchained** [comment]
There was actually github workflow for this but we forgot to adjust the config after we migrate it into it's own repository so it wasn't running.

See my change that just enabled it: https://github.com/soonaverse/app/commit/9c51d805a6f58f03c9bc7e9111a04c10b73e9ba0

We don't have any tests at the moment. Feel free to re-open this issue if you want to build more automated github workflows. 

There is also Cloudflare workflow that automatically creates unique URL for each PR where the changes can be tested.
