### ISSUE TITLE
NFT attribute 'soldOn' not updated in API

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/app#39]
**Describe the bug**
Dear devs, 

someone reported the following on discord (bugissue-372) which only applies to the API data but directly on soonaverse it seems fine (see screenshot below).

One example NFT that was bought a few days ago (bug also applies to other NFTs bought recently): _https://soonaverse.com/nft/0x8ed8772ed3dec94fd9b6926d4c26c7850c8766ad_

_"The soldOn field is not updated and is still set to Sunday 30 October 2022:_
_https://api.build5.com/api/getById?collection=nft&uid=0x8ed8772ed3dec94fd9b6926d4c26c7850c8766ad"_

_"The soldOn.\_seconds field has a timestamp of 1667154677"_

_"Update: experienced the same with some other NFTs that i bought today. Seems like soldOn is not updated if price < a certain threshold (maybe 15mi/smr?)"_

**Screenshots**
![Screenshot_20230817_203917_Opera_Touch](https://github.com/soonaverse/app/assets/104099536/f215a139-fa78-49e8-9234-a268418986d3)

Greetings,
Bananu

**Comment by adamunchained** [comment]
Not that's not how soldOn works.

soldOn is the date/time when the NFT was initially sold from the artists. It's never updated after. 

lastTradedOn contains last trade date/time.
