### ISSUE TITLE
Hyperlink broken in .md file.

### ISSUE THREAD

**Issue by Deep-Sea-888** [soonaverse/app#42]
**Describe the bug**
The link is broken on the CONTRIBUTING.md page.

**To Reproduce**
1. Go to ['...'](https://github.com/soonaverse/app/blob/master/CONTRIBUTING.md)
2. Click on Facebook link found at the bottom of .md under the References paragraph.
4. See that the link brings you to a broken page.

**Expected behavior**
A clear and concise description of what you expected to happen. Expected to be brought to a draft .md document.

**Screenshots**
Not Applicable.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [Chrome]
 - Version [e.g. 11]

**Smartphone (please complete the following information):**

**Additional context**
No additional context.

**Comment by adamunchained** [comment]
I'm assuming it was the link to issues, fixed!
