### ISSUE TITLE
NftPurchaseTangleRequest without withdraw

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/app#44]
Would it be possible to add a field to the metadata to prevent automatic withdraw after purchase for cases where the sender's address is already a verified address for a Soonaverse account.

Thanks!

**Comment by adamunchained** [comment]
Please add option flag "disableWithdraw". This flag is by default false. Means system behaves the same.

if "true", skip "Nft Withdraw".

**Comment by adamunchained** [comment]
Delivered
