### ISSUE TITLE
Extend auction on last-minute bids 

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/app#46]
I would like to request the following feature: 

Ability to automatically extend auctions for 5 min if a bid comes in within 5 minutes until the end of the auction.

Thanks 🙏

**Comment by adamunchained** [comment]
@flyingrabbit-lab - please extend setForSaleNftControl with flag "extendAuctionPeriod" (unix timestamp, same type as auctionFrom). This is undefined by default. If undefined it behaves as it's implemented at the moment. 

If set, extend auctionTo and auctionLength with "extendAuctionPeriod" period.

**Comment by adamunchained** [comment]
Delivered
