### ISSUE TITLE
Allow to search NFTs by Collection name under Profile NFTs tab

### ISSUE THREAD

**Issue by emmap3-do** [soonaverse/app#48]
On Profile page, under NFTs tab, the search input seems to be searching by NFT name. But it would be nice if it also searches by Collection name. Otherwise, sometimes it's hard to find what you're looking for. 

See example attached. I've been searching for "n3tsu" but since it is not part of the nft name, there are no results. I only get the result when I hit the exact name or partial match of that name. 
It's worse when you have multiple nfts from the same collection, you can't filter by collection name to see all of them, you need to search one by one by their names.

I understand that a better setup of each nft name (by the collection owner) would solve this, but I think this could happen a lot and adjusting the search functionality so that it considers the collection name can be an enhacement.

![image](https://github.com/soonaverse/app/assets/124573743/bfa8dce4-0fd9-4ea5-b2f5-e1374b695ede)

**Comment by emmap3-do** [comment]
@adamunchained 
I tried to look into this one, but couldn't find the place where to adjust it. 
Maybe it needs to be adjusted within the API?

**Comment by adamunchained** [comment]
Re-opening as per Emmap3 request
