### ISSUE TITLE
Filter NFT Collections by token (All / IOTA / SMR)

### ISSUE THREAD

**Issue by emmap3-do** [soonaverse/app#49]
While navigating through "NFT Collections" (ie. https://soonaverse.com/market/collections) it would be nice to have the ability to quickly filter by token (eg. ALL / IOTA / SMR / ...) to narrow down the search results and fit user's interest. This may be added under the "Filters&Sort" section or as pills buttons next to the search field.

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- new search options needs to be added
