### ISSUE TITLE
TangleRequests return credit

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/app#52]
**Describe the bug**
Calling NftDepositTangleRequest or NftPurchaseTangleRequest multiple times in a row returns as a credit (return of funds or NFT).

**To Reproduce**
1. Deposit 1 nft using the NftDepositTangleRequest
2. Wait until transaction is confirmed on tangle (about 10 sec)
3. Deposit another nft using the NftDepositTangleRequest
4. 2nd deposit is credited

**Expected behavior**
Queue processing of ouputs from a specific sender for TangleRequests

**Comment by flyingrabbit-lab** [comment]
@ivanbeerlama I could not reproduce this error, in my test scenarios things work fine. Could you send me some tangle transactions, maybe I find something there?

**Comment by ivanbeerlama** [comment]
https://explorer.shimmer.network/shimmer/block/0x7b305baf2b5f5069b24c400b16bd4f1feb19cb3a1faaa1c5e19843f265a0ca39?tab=Payload

It looks like i'm getting the response: "You have currently another order in progress."

**Comment by flyingrabbit-lab** [comment]
In the description you provided a scenario about depositing an NFT, but this block is about purchasing an NFT.
Could you describe what you did while purchasing and how to reproduce this issue?

**Comment by ivanbeerlama** [comment]
Basically 2 NftPurchaseTangleRequest's for 2 different NFTs. 

1. NftPurchaseTangleRequest nft #1 
2. Wait until tx is confirmed (about 10 sec)
3. NftPurchaseTangleRequest nft #2
4. Wait until tx is confirmed
5. After a while (30 sec) soon picks up request at TangleRequest address and purchases nft #1
6. The NftPurchaseTangleRequest for nft #2 is credited

This means that between my NftPurchaseTangleRequests i need to wait about ~60 sec for both purchases to succeed.

The same happens with NftDepositTangleRequest

**Comment by flyingrabbit-lab** [comment]
Purchasing multiple NFTs with OTR is fixed and soon will be deployed.
I still can not reproduce the depositing error with OTR though. Could you provide an example block id?

**Comment by adamunchained** [comment]
This has been fixed.
