### ISSUE TITLE
Orderbook decimals do not match actual orders

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/app#63]
The 4th decimal of an entry in the orderbook is displayed incorrectly:

![image](https://github.com/soonaverse/app/assets/99087735/4d003745-1748-40ae-9a8c-c5eb7e5b2ebf)

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- improve consistency of rounding on different places within the front-end
