### ISSUE TITLE
OTR NFT_SET_FOR_SALE cancels ongoing auctions - Funds not returned

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/app#64]
**Highest bid does not return to highest bidder!**

To reproduce:

1. List nft for auction
2. Get 0 or more bids
3. Perform the following tangle request:

```
  metadata = {
        "request": {
            "requestType": "NFT_SET_FOR_SALE",
            "availableFrom": int(time.time() * 1000 + 15 * 60 * 1000),
            "nft": key,
            "price": price,
        }
```

4. NFT is listed for 'price' and auction is canceled
5. Funds do not return to bidder

Example:
Canceled auction:
https://soonaverse.com/nft/0xd638f80b395b1084c8fac04307a3d22762225eed
This is the bidder: https://soonaverse.com/member/0x1b87c13ced5867ca86f1d882793b075d7875dfec/transactions
Bid tx: https://explorer.shimmer.network/shimmer/block/0xbe6cd800d4a85501179ed9099c49cc9c1fc1f8a1beddd1495f3054be44377c89
The 750 SMR is not credited, and is in limbo somewhere.

OTR request: https://explorer.shimmer.network/shimmer/block/0xee3f4fa870bd4a3e751fec05ca733af19604f87e7ad601681b8faf5804a807df
OTR response:
https://explorer.shimmer.network/shimmer/block/0xe33e89f51aa893c8754ab3e6cc77473236ec8823d281e69b54176670faa72f05

**Comment by flyingrabbit-lab** [comment]
@ivanbeerlama This has been fixed and the funds should be credited back.
