### ISSUE TITLE
SDPR Real-time rewards monitor for more transparency:

### ISSUE THREAD

**Issue by lomax-zksn** [soonaverse/app#65]
I suggest a website monitor for SDPR that shows transparently in real time how much SMR is earned from Service module providers via SDPR? This would massively increase trust in this mechanism and $SOON utility.

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- this can be achieved by listening to transactions and showing them. All this data are available
