### ISSUE TITLE
Verifying SMR Address for a space does inform user about proposal

### ISSUE THREAD

**Issue by f15hfood** [soonaverse/app#66]
**Describe the bug**
I want to verify my SMR address, paying the needed SMR, it says verificaion finished, but nothing happens, SMR will get refunded, but the status "unverified" keep as it is.

**To Reproduce**
1. Go to 'https://soonaverse.com/space/0xd04b96aed8c3ab9fd9a94072817db16de8b95285/collections'
2. Click on 'manage'
3. Click verify and send the needed SMR
4. See error -->  " Not yet verified "

**Expected behavior**
I would expect that my SMR adress gets verified for my collections.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 117.0.5938.92

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
@flyingrabbit-lab - can you check this please?

**Comment by flyingrabbit-lab** [comment]
@f15hfood Could you provide me the tangle transaction id with which you paid for the verification?

**Comment by f15hfood** [comment]
yah sure, tried it again today: 0xff64cfca848c13fd51de530b542c3d3516e3c6e1d79f2ca85c440085615f8e86
https://explorer.shimmer.network/shimmer/transaction/0xff64cfca848c13fd51de530b542c3d3516e3c6e1d79f2ca85c440085615f8e86

**Comment by flyingrabbit-lab** [comment]
Ah, now I understand what the issue here is. When you verify your space address it does not instantly set's the address. It creates a proposal that needs to be approved
https://soonaverse.com/space/0xd04b96aed8c3ab9fd9a94072817db16de8b95285/proposals

**Comment by flyingrabbit-lab** [comment]
@adamunchained This happened before, I think we should update to UI to display a clear message pointing users to proposals page.

**Comment by f15hfood** [comment]
thanks a lot @flyingrabbit-lab and @adamunchained  yah I was not aware if there are 2 guardians, that there will upcome a proposal

**Comment by adamunchained** [comment]
Will tweak UI.

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- UI needs to be tweaked to tell user there is a proposal that needs to voted on. Or ideally, it even redirects user to it.
