### ISSUE TITLE
SOON tokens disappeared after faulty Soonaverse tx

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/app#72]
**Describe the bug**
Hi together,

User from #bugissue-415 on discord (https://soonaverse.com/member/0xac2c8bdc99cc8edd3db4d43756d2b021953d0423/transactions) tried to stake SOON but soonaverse messed up the tx data a bit it seems bc in the tx data at the bottom here https://explorer.shimmer.network/shimmer/block/0x030d9b5ef99940c90fd010d73a892e1d80054dfb9baa8001008e253687582622?tab=Payload the quantity of SOON is zero
![image-36.png](https://github.com/soonaverse/app/assets/104099536/6652b011-2fbc-461a-b14d-3ad017c2050c)

User also found a way to reproduce it. But their SOON is still missing though. Usually upon staking there is a near immediate "credit" tx umin the users tx history (currently moving NFTs to another wallet btw)

Could u pls check this and how the user gets their SOON back?

Thx and kind regards,
Bananu

**To Reproduce**
if you start staking, you will see these pop-ups below
![image-44.png](https://github.com/soonaverse/app/assets/104099536/0296e130-f667-4bd3-b327-b3ccb5d1232d)

![image-49.png](https://github.com/soonaverse/app/assets/104099536/b4684af3-d08f-4335-862f-9820ca31049a)

if you click the X button in the upper right corner, and then click the 'stake more' button in the <https://soonaverse.com/member/0xac2c8bdc99cc8edd3db4d43756d2b021953d0423/activity> again, then you see this pop-up which shows your total staked value is 0 instead of 2,000

![image-39.png](https://github.com/soonaverse/app/assets/104099536/783ebbae-b298-448a-8670-16f3e0ce51d1)

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- this seems to be an UI bug. It doesn't remember how much user indicated they want to stake. B5 Platform accepts any amount.
