### ISSUE TITLE
Double outgoing tx via --> Firefly Soonaverse

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/app#73]
**Describe the bug**
Hi guys,

a user reported in discord ticket #bugissue-418 the following:
======================

Hi, 

Something odd happened yesterday in two instances where I sold a bit of SOON. (to get funds to provide more liquidity for the pool 🙂 )
In both instances the transactions were sent twice from my firefly wallet. That means 

Instance 1: Sold 1100 SOON. Two outbound transactions was sent from Firefly
Instance 2: Sold 2300 SOON. Again two outbound transactions was sent from Firefly.  

I used the deeplink in both instances...
![image-52.png](https://github.com/soonaverse/app/assets/104099536/10845342-d114-48f5-b89f-d552caeb423b)

That means I am missing 3400 SOON. that i believe has been received by Soonaverse. would it be possible to check (and send it back 🙂 ?

The transactions from the soonaverse history page are: 

Transaction 1 (2300 SOON) https://explorer.shimmer.network/shimmer/block/0xc5b368e3ce9be7bad3ebcdabb74c37710edcc192a3bcb9631c320b20b7f34395
Transaction 2 (1100 SOON)
https://explorer.shimmer.network/shimmer/block/0xbd5c3fd82716de42b372a6660c0a473a33401ba17f8a3abeeec59341a38c8e30

From the Firefly wallet I have 4 transactions as follows: 

Transaction 1 (2300 SOON): https://explorer.shimmer.network/shimmer/transaction/0xf18df5d4f847f25fec5d9d451c73bf30d7b12f8b2e83223a9e088043edb2380f

Transaction 2: (2300 SOON): https://explorer.shimmer.network/shimmer/transaction/0x4e0ef81bd8c67955241780bb8b52a33b1cc113e29637ad2bb5cc654c4987fb1f

Transaction 3: (1100 SOON)
https://explorer.shimmer.network/shimmer/transaction/0x6d03b67097d0835200a562491f2933cc2cecedf7e60cd130c12f5af8969e04cb

Transaction 4: (1100 SOON)
https://explorer.shimmer.network/shimmer/transaction/0x18165fe02bcc2a9d0048537bbd8aaf40e7fbcbf64495af022ab07d3bcf5103cd

Kind regards,
Bananu

**Comment by Derivs** [comment]
This ticket can be closed.

It has been busy days. finally had time to investigate and try and validate the issue.
Seems it is just a firefly UI issue.
