### ISSUE TITLE
Add option to remove avatar

### ISSUE THREAD

**Issue by andyfront0** [soonaverse/app#74]
**Is your feature request related to a problem? Please describe.**
I can't remove the avatar from my profile and save the profile. "avatarNft" always needs a string.

**Describe the solution you'd like**
I want to remove the avatar from my profile and leave an empty default image

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- front end needs to allow unsetting of it.
