### ISSUE TITLE
Can't change NFT avatar

### ISSUE THREAD

**Issue by multifolio** [soonaverse/app#78]
**Describe the bug**
Can not change NFT avatar.

**To Reproduce**
1. Have at least two NFTs 
2. Set one as avatar 
3. Try to change to the other one
4. Second avatar wont show up in dropdown list.

**Expected behavior**
Expected to change avatar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser firefox

**Additional context**
NFT that is stuck: https://soonaverse.com/nft/0xe2abde41c8b08d19e073b9456e3a3c9c5313c2d426217e625eb73c39122f5461

**Comment by adamunchained** [comment]
Is this still an issue?
