### ISSUE TITLE
Collection appears as minted out when it's not.

### ISSUE THREAD

**Issue by Tanglestrong** [soonaverse/app#81]
**Describe the bug**
While minting the Souls of TangleSwap collection I encountered a bug where despite having +230 Souls NFTs to be minted out the UI was displaying it as ''Sale ended''

https://soonaverse.com/collection/0x740233f719efd6b7314b7e773c6ce09d6d831a71

**To Reproduce**
1. Go to https://soonaverse.com/collection/0x740233f719efd6b7314b7e773c6ce09d6d831a71, minting page is not available anymore although I have screenshots of when the ''Sale ended'' issue happened

**Expected behavior**
I should be able to keep minting until all the ''unsold'' Souls are effectively ''sold''

**Screenshots**
![Captura_de_pantalla_2023-11-01_a_las_15](https://github.com/soonaverse/app/assets/101262115/e9db314f-e1ee-4db1-bd76-d1634690b76e)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version Ventura 13.4

**Additional context**
I think the issue could be somehow related to the difference between the amount of Souls that are shown as deposited - Amount of total NFTs, since that difference is similar to the one amount of NFTs that were left to be minted

**Comment by adamunchained** [comment]
@flyingrabbit-lab - could check this? It seems some NFTs were set available for sale but not un-hidden. They should be unhidden as the place holders is set to hidden?

**Comment by adamunchained** [comment]
@flyingrabbit-lab - I believe the issue here is that placeholderNft is set as hidden even though it should actually stay visible until the collection "unsold" NFTs are fully sold out. Please tweak.

this only applies to collections that were minted and user didn't take ownership of unsold NFTs

**Comment by adamunchained** [comment]
This issue has now been resolved.
