### ISSUE TITLE
Remove option to create NFT collections without minting

### ISSUE THREAD

**Issue by DiePutze5853** [soonaverse/app#86]
Since Soonaverse was launched before Iota or Shimmer had NFT capabilities there are a lot of collections which have not been migrated to a network yet. 
Back then it was a good choice to allow artists and spaces to "pre-release" their collections while everyone had to wait for IF to deliver.
Now that Iota and Shimmer have NFT capabilities, the option to create unmigrated/unminted collections should be removed, to protect users from buying into projects that don't have the funds to cover the necessary storage deposit required for minting the collection.

To still allow artists and spaces to release collections without the funds to mint the collection I have proposed an alternative [here](https://github.com/soonaverse/app/issues/85)

**Comment by adamunchained** [comment]
Please change the logic on the backend to remove approval function and collection will only get approved once minted. 

Once done, assign back to me and I'll tweak front-end to handle the different UX Flow.

**Comment by adamunchained** [comment]
@DiePutze5853 - this has been tweaked and released into the production. It'll be published within next 30 minutes. We did as hotfix since our next planned release is far out.
