### ISSUE TITLE
Accounts are hidden, not-retrievable 

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#98]
**Describe the bug**
There are many recent users and accounts that exist but are not able to be found through search or even directly placing address in url.
![image](https://github.com/soonaverse/app/assets/112674501/a6d81448-69bc-486d-9f41-845e976a539e)

**To Reproduce**
1. Try searching for this account in the discover bar (currently named AlecM): https://soonaverse.com/member/0x3ffbc221b2215d6e7d9c863fb44616a1ae042017/badges
2. Now delete the "/badges" from the url above and you will get a 404 error.

**Expected behavior**
Accounts should normally be able to be found in the discover or search functions, as well as in private listings but is not the case with many of these accounts.  Similarly, the urls of normally behaving accounts will appear if placing the address after soonaverse.com/member/0x.... but these accounts require "/badges" "/nft" etc.

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- seems routing on Angular router is not properly configured

**Comment by iotaflea** [comment]
this issue seems to be resolved now
