### ISSUE TITLE
Staked SOON not returned to Wallet

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/app#99]
**Describe the bug**
User Profile: 0x4E04a3954c04579317A8C183c8838CF0e3F44Fe1
Transaction : 0x0d9cfaf98453f9d7941ac721b66774c1e41f7bc383ed83287e5f09e43a81c7c2

I have sent larger amounts from Soonarverse to my shimmer address. In my profile under activities total staking I only see the old amount, but when I look under active staking tokens they are shown to me from the tokens where I received them from the last airdrop disappeared and with my tokens I only received a small amount in my shimmer wallet that I actually transferred there

I have now received almost all transactions in my wallet, only maybe. I'm still missing a few soon, but I transferred the soon transaction above back into staking and didn't get it back locked

Its not solved the 7,282 soon are don't arrived back in locked to my wallet

Ticket: https://discord.com/channels/892481940953915433/1181896445280927786

**Expected behavior**
SOON Tokens returned to wallet locked

**Screenshots**
![IMG_20231208_171043](https://github.com/soonaverse/app/assets/44786846/0c119202-d98f-4cef-a098-938022724ac5)

**Comment by flyingrabbit-lab** [comment]
SOON tokens are returned to wallet locked.
